//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Adviser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Adviser">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.epistandards.com/4.3}Identifier"/>
 *         &lt;element name="FPSId" type="{http://www.epistandards.com/4.3}Identifier" minOccurs="0"/>
 *         &lt;element name="APIRPRI" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Title" type="{http://www.epistandards.com/4.3}Title" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.epistandards.com/4.3}LastName"/>
 *         &lt;element name="FirstName" type="{http://www.epistandards.com/4.3}FirstName"/>
 *         &lt;element name="MiddleName" type="{http://www.epistandards.com/4.3}MiddleName" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://www.epistandards.com/4.3}Gender" minOccurs="0"/>
 *         &lt;element name="ContactDetails" type="{http://www.epistandards.com/4.3}ContactDetails" minOccurs="0"/>
 *         &lt;element name="BusinessDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="2">
 *                   &lt;element name="DealerGroup" type="{http://www.epistandards.com/4.3}DealerGroup"/>
 *                   &lt;element name="Business">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="150"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="APIRPRI" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;length value="9"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ABN" type="{http://www.epistandards.com/4.3}ABN" minOccurs="0"/>
 *                             &lt;element name="ACNorARBN" type="{http://www.epistandards.com/4.3}ACN" minOccurs="0"/>
 *                             &lt;element name="AFSL" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="BranchName" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="60"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="ABNBranch" type="{http://www.epistandards.com/4.3}ABN" minOccurs="0"/>
 *                             &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Adviser", propOrder = {
    "id",
    "fpsId",
    "apirpri",
    "title",
    "lastName",
    "firstName",
    "middleName",
    "gender",
    "contactDetails",
    "businessDetails",
    "epiExtension"
})
@XmlSeeAlso({
    com.gbst.customdatasource.xplan.domain.EPIDataResponse.Advisers.Adviser.class,
    com.gbst.customdatasource.xplan.domain.Intermediary.Adviser.class
})
public class Adviser {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "FPSId")
    protected String fpsId;
    @XmlElement(name = "APIRPRI")
    protected String apirpri;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "LastName", required = true)
    protected String lastName;
    @XmlElement(name = "FirstName", required = true)
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "Gender")
    protected Gender gender;
    @XmlElement(name = "ContactDetails")
    protected ContactDetails contactDetails;
    @XmlElement(name = "BusinessDetails")
    protected Adviser.BusinessDetails businessDetails;
    @XmlElement(name = "EPIExtension")
    protected EPIExtension epiExtension;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the fpsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPSId() {
        return fpsId;
    }

    /**
     * Sets the value of the fpsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPSId(String value) {
        this.fpsId = value;
    }

    /**
     * Gets the value of the apirpri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPIRPRI() {
        return apirpri;
    }

    /**
     * Sets the value of the apirpri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPIRPRI(String value) {
        this.apirpri = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link Gender }
     *     
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link Gender }
     *     
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the contactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ContactDetails }
     *     
     */
    public ContactDetails getContactDetails() {
        return contactDetails;
    }

    /**
     * Sets the value of the contactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactDetails }
     *     
     */
    public void setContactDetails(ContactDetails value) {
        this.contactDetails = value;
    }

    /**
     * Gets the value of the businessDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Adviser.BusinessDetails }
     *     
     */
    public Adviser.BusinessDetails getBusinessDetails() {
        return businessDetails;
    }

    /**
     * Sets the value of the businessDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adviser.BusinessDetails }
     *     
     */
    public void setBusinessDetails(Adviser.BusinessDetails value) {
        this.businessDetails = value;
    }

    /**
     * Gets the value of the epiExtension property.
     * 
     * @return
     *     possible object is
     *     {@link EPIExtension }
     *     
     */
    public EPIExtension getEPIExtension() {
        return epiExtension;
    }

    /**
     * Sets the value of the epiExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPIExtension }
     *     
     */
    public void setEPIExtension(EPIExtension value) {
        this.epiExtension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="2">
     *         &lt;element name="DealerGroup" type="{http://www.epistandards.com/4.3}DealerGroup"/>
     *         &lt;element name="Business">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="150"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="APIRPRI" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;length value="9"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ABN" type="{http://www.epistandards.com/4.3}ABN" minOccurs="0"/>
     *                   &lt;element name="ACNorARBN" type="{http://www.epistandards.com/4.3}ACN" minOccurs="0"/>
     *                   &lt;element name="AFSL" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="BranchName" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="60"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="ABNBranch" type="{http://www.epistandards.com/4.3}ABN" minOccurs="0"/>
     *                   &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dealerGroupOrBusiness"
    })
    public static class BusinessDetails {

        @XmlElements({
            @XmlElement(name = "DealerGroup", type = DealerGroup.class),
            @XmlElement(name = "Business", type = Adviser.BusinessDetails.Business.class)
        })
        protected List<Object> dealerGroupOrBusiness;

        /**
         * Gets the value of the dealerGroupOrBusiness property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dealerGroupOrBusiness property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDealerGroupOrBusiness().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DealerGroup }
         * {@link Adviser.BusinessDetails.Business }
         * 
         * 
         */
        public List<Object> getDealerGroupOrBusiness() {
            if (dealerGroupOrBusiness == null) {
                dealerGroupOrBusiness = new ArrayList<Object>();
            }
            return this.dealerGroupOrBusiness;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="150"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="APIRPRI" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="9"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ABN" type="{http://www.epistandards.com/4.3}ABN" minOccurs="0"/>
         *         &lt;element name="ACNorARBN" type="{http://www.epistandards.com/4.3}ACN" minOccurs="0"/>
         *         &lt;element name="AFSL" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="BranchName" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="60"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ABNBranch" type="{http://www.epistandards.com/4.3}ABN" minOccurs="0"/>
         *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "apirpri",
            "abn",
            "acNorARBN",
            "afsl",
            "branchName",
            "abnBranch",
            "epiExtension"
        })
        public static class Business {

            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "APIRPRI")
            protected String apirpri;
            @XmlElement(name = "ABN")
            protected String abn;
            @XmlElement(name = "ACNorARBN")
            protected String acNorARBN;
            @XmlElement(name = "AFSL")
            protected String afsl;
            @XmlElement(name = "BranchName")
            protected String branchName;
            @XmlElement(name = "ABNBranch")
            protected String abnBranch;
            @XmlElement(name = "EPIExtension")
            protected EPIExtension epiExtension;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the apirpri property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAPIRPRI() {
                return apirpri;
            }

            /**
             * Sets the value of the apirpri property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAPIRPRI(String value) {
                this.apirpri = value;
            }

            /**
             * Gets the value of the abn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getABN() {
                return abn;
            }

            /**
             * Sets the value of the abn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setABN(String value) {
                this.abn = value;
            }

            /**
             * Gets the value of the acNorARBN property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getACNorARBN() {
                return acNorARBN;
            }

            /**
             * Sets the value of the acNorARBN property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setACNorARBN(String value) {
                this.acNorARBN = value;
            }

            /**
             * Gets the value of the afsl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAFSL() {
                return afsl;
            }

            /**
             * Sets the value of the afsl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAFSL(String value) {
                this.afsl = value;
            }

            /**
             * Gets the value of the branchName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBranchName() {
                return branchName;
            }

            /**
             * Sets the value of the branchName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBranchName(String value) {
                this.branchName = value;
            }

            /**
             * Gets the value of the abnBranch property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getABNBranch() {
                return abnBranch;
            }

            /**
             * Sets the value of the abnBranch property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setABNBranch(String value) {
                this.abnBranch = value;
            }

            /**
             * Gets the value of the epiExtension property.
             * 
             * @return
             *     possible object is
             *     {@link EPIExtension }
             *     
             */
            public EPIExtension getEPIExtension() {
                return epiExtension;
            }

            /**
             * Sets the value of the epiExtension property.
             * 
             * @param value
             *     allowed object is
             *     {@link EPIExtension }
             *     
             */
            public void setEPIExtension(EPIExtension value) {
                this.epiExtension = value;
            }

        }

    }

}
