//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Asset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Asset">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.epistandards.com/4.3}Identifier"/>
 *         &lt;element name="AssetType" type="{http://www.epistandards.com/4.3}AssetType"/>
 *         &lt;element name="Description">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RealEstate" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TitleType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Community"/>
 *                         &lt;enumeration value="Unit"/>
 *                         &lt;enumeration value="Strata"/>
 *                         &lt;enumeration value="Stratum"/>
 *                         &lt;enumeration value="Company"/>
 *                         &lt;enumeration value="CrownLand"/>
 *                         &lt;enumeration value="CrownLease"/>
 *                         &lt;enumeration value="Freehold"/>
 *                         &lt;enumeration value="GroupTitlesPlan"/>
 *                         &lt;enumeration value="Leasehold"/>
 *                         &lt;enumeration value="Moiety"/>
 *                         &lt;enumeration value="Purple"/>
 *                         &lt;enumeration value="Other"/>
 *                         &lt;enumeration value="None"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PropertyType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="100"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ZoningType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="100"/>
 *                         &lt;enumeration value="Residential"/>
 *                         &lt;enumeration value="Commercial"/>
 *                         &lt;enumeration value="CommercialResidential"/>
 *                         &lt;enumeration value="Rural"/>
 *                         &lt;enumeration value="RuralResidential"/>
 *                         &lt;enumeration value="ShortStayAccommodation"/>
 *                         &lt;enumeration value="Urban"/>
 *                         &lt;enumeration value="Other"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Address" type="{http://www.epistandards.com/4.3}Address"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Owners">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Owner" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;choice>
 *                               &lt;element name="ClientId" type="{http://www.epistandards.com/4.3}Identifier"/>
 *                               &lt;element name="AccountID" type="{http://www.epistandards.com/4.3}Identifier"/>
 *                             &lt;/choice>
 *                             &lt;element name="PercentageOfOwnership" type="{http://www.epistandards.com/4.3}PositivePercentage" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Status">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="AwaitingMonies"/>
 *               &lt;enumeration value="Cancelled"/>
 *               &lt;enumeration value="Existing"/>
 *               &lt;enumeration value="Lapsed"/>
 *               &lt;enumeration value="NonContributory"/>
 *               &lt;enumeration value="NotProceededWith"/>
 *               &lt;enumeration value="PaidUp"/>
 *               &lt;enumeration value="PendingLapsed"/>
 *               &lt;enumeration value="Recommended"/>
 *               &lt;enumeration value="Renewal"/>
 *               &lt;enumeration value="Transferred"/>
 *               &lt;enumeration value="UnderClaim"/>
 *               &lt;enumeration value="Underwriting"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AcquisitionDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="InitialValue" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                   &lt;choice maxOccurs="2">
 *                     &lt;element name="EstablishmentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                     &lt;element name="AcquisitionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ValuationDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CurrentValue" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                   &lt;element name="ValuationType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Market"/>
 *                         &lt;enumeration value="Government"/>
 *                         &lt;enumeration value="Estimate"/>
 *                         &lt;enumeration value="Other"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ValuationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="MaturityValue" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *                   &lt;element name="MaturityDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="CapitalValue" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AssetCurrency" type="{http://www.epistandards.com/4.3}CurrencyCode"/>
 *         &lt;element name="FXAccountCurrency" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="DisposalDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DisposalValue" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                   &lt;element name="DisposalDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Contributions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                   &lt;element name="Frequency" type="{http://www.epistandards.com/4.3}PaymentFrequency"/>
 *                   &lt;element name="AnnualEscalation" type="{http://www.epistandards.com/4.3}PositivePercentage" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Income" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                   &lt;element name="Frequency" type="{http://www.epistandards.com/4.3}PaymentFrequency"/>
 *                   &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="ReinvestIncome" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Payment" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PaymentMethod" type="{http://www.epistandards.com/4.3}PaymentMethod"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Notes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Note" type="{http://www.epistandards.com/4.3}Note" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AssociatedLiabilities" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Liability" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.epistandards.com/4.3}Identifier"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Delete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Asset", propOrder = {
    "id",
    "assetType",
    "description",
    "realEstate",
    "owners",
    "status",
    "acquisitionDetails",
    "valuationDetails",
    "assetCurrency",
    "fxAccountCurrency",
    "disposalDetails",
    "contributions",
    "income",
    "payment",
    "notes",
    "associatedLiabilities",
    "delete"
})
public class Asset {

    @XmlElement(name = "Id", required = true)
    protected String id;
    @XmlElement(name = "AssetType", required = true)
    protected AssetType assetType;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "RealEstate")
    protected Asset.RealEstate realEstate;
    @XmlElement(name = "Owners", required = true)
    protected Asset.Owners owners;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "AcquisitionDetails", required = true)
    protected Asset.AcquisitionDetails acquisitionDetails;
    @XmlElement(name = "ValuationDetails", required = true)
    protected Asset.ValuationDetails valuationDetails;
    @XmlElement(name = "AssetCurrency", required = true)
    protected CurrencyCode assetCurrency;
    @XmlElement(name = "FXAccountCurrency")
    protected MonetaryAmount fxAccountCurrency;
    @XmlElement(name = "DisposalDetails")
    protected Asset.DisposalDetails disposalDetails;
    @XmlElement(name = "Contributions")
    protected Asset.Contributions contributions;
    @XmlElement(name = "Income")
    protected Asset.Income income;
    @XmlElement(name = "Payment")
    protected Asset.Payment payment;
    @XmlElement(name = "Notes")
    protected Asset.Notes notes;
    @XmlElement(name = "AssociatedLiabilities")
    protected Asset.AssociatedLiabilities associatedLiabilities;
    @XmlElement(name = "Delete")
    protected boolean delete;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the assetType property.
     * 
     * @return
     *     possible object is
     *     {@link AssetType }
     *     
     */
    public AssetType getAssetType() {
        return assetType;
    }

    /**
     * Sets the value of the assetType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetType }
     *     
     */
    public void setAssetType(AssetType value) {
        this.assetType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the realEstate property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.RealEstate }
     *     
     */
    public Asset.RealEstate getRealEstate() {
        return realEstate;
    }

    /**
     * Sets the value of the realEstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.RealEstate }
     *     
     */
    public void setRealEstate(Asset.RealEstate value) {
        this.realEstate = value;
    }

    /**
     * Gets the value of the owners property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.Owners }
     *     
     */
    public Asset.Owners getOwners() {
        return owners;
    }

    /**
     * Sets the value of the owners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.Owners }
     *     
     */
    public void setOwners(Asset.Owners value) {
        this.owners = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the acquisitionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.AcquisitionDetails }
     *     
     */
    public Asset.AcquisitionDetails getAcquisitionDetails() {
        return acquisitionDetails;
    }

    /**
     * Sets the value of the acquisitionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.AcquisitionDetails }
     *     
     */
    public void setAcquisitionDetails(Asset.AcquisitionDetails value) {
        this.acquisitionDetails = value;
    }

    /**
     * Gets the value of the valuationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.ValuationDetails }
     *     
     */
    public Asset.ValuationDetails getValuationDetails() {
        return valuationDetails;
    }

    /**
     * Sets the value of the valuationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.ValuationDetails }
     *     
     */
    public void setValuationDetails(Asset.ValuationDetails value) {
        this.valuationDetails = value;
    }

    /**
     * Gets the value of the assetCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCode }
     *     
     */
    public CurrencyCode getAssetCurrency() {
        return assetCurrency;
    }

    /**
     * Sets the value of the assetCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCode }
     *     
     */
    public void setAssetCurrency(CurrencyCode value) {
        this.assetCurrency = value;
    }

    /**
     * Gets the value of the fxAccountCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getFXAccountCurrency() {
        return fxAccountCurrency;
    }

    /**
     * Sets the value of the fxAccountCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setFXAccountCurrency(MonetaryAmount value) {
        this.fxAccountCurrency = value;
    }

    /**
     * Gets the value of the disposalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.DisposalDetails }
     *     
     */
    public Asset.DisposalDetails getDisposalDetails() {
        return disposalDetails;
    }

    /**
     * Sets the value of the disposalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.DisposalDetails }
     *     
     */
    public void setDisposalDetails(Asset.DisposalDetails value) {
        this.disposalDetails = value;
    }

    /**
     * Gets the value of the contributions property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.Contributions }
     *     
     */
    public Asset.Contributions getContributions() {
        return contributions;
    }

    /**
     * Sets the value of the contributions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.Contributions }
     *     
     */
    public void setContributions(Asset.Contributions value) {
        this.contributions = value;
    }

    /**
     * Gets the value of the income property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.Income }
     *     
     */
    public Asset.Income getIncome() {
        return income;
    }

    /**
     * Sets the value of the income property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.Income }
     *     
     */
    public void setIncome(Asset.Income value) {
        this.income = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.Payment }
     *     
     */
    public Asset.Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.Payment }
     *     
     */
    public void setPayment(Asset.Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.Notes }
     *     
     */
    public Asset.Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.Notes }
     *     
     */
    public void setNotes(Asset.Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the associatedLiabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Asset.AssociatedLiabilities }
     *     
     */
    public Asset.AssociatedLiabilities getAssociatedLiabilities() {
        return associatedLiabilities;
    }

    /**
     * Sets the value of the associatedLiabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asset.AssociatedLiabilities }
     *     
     */
    public void setAssociatedLiabilities(Asset.AssociatedLiabilities value) {
        this.associatedLiabilities = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     */
    public boolean isDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     */
    public void setDelete(boolean value) {
        this.delete = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InitialValue" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *         &lt;choice maxOccurs="2">
     *           &lt;element name="EstablishmentDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *           &lt;element name="AcquisitionDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initialValue",
        "establishmentDateOrAcquisitionDate"
    })
    public static class AcquisitionDetails {

        @XmlElement(name = "InitialValue", required = true)
        protected MonetaryAmount initialValue;
        @XmlElementRefs({
            @XmlElementRef(name = "EstablishmentDate", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "AcquisitionDate", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<XMLGregorianCalendar>> establishmentDateOrAcquisitionDate;

        /**
         * Gets the value of the initialValue property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getInitialValue() {
            return initialValue;
        }

        /**
         * Sets the value of the initialValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setInitialValue(MonetaryAmount value) {
            this.initialValue = value;
        }

        /**
         * Gets the value of the establishmentDateOrAcquisitionDate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the establishmentDateOrAcquisitionDate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEstablishmentDateOrAcquisitionDate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
         * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
         * 
         * 
         */
        public List<JAXBElement<XMLGregorianCalendar>> getEstablishmentDateOrAcquisitionDate() {
            if (establishmentDateOrAcquisitionDate == null) {
                establishmentDateOrAcquisitionDate = new ArrayList<JAXBElement<XMLGregorianCalendar>>();
            }
            return this.establishmentDateOrAcquisitionDate;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Liability" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Id" type="{http://www.epistandards.com/4.3}Identifier"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "liability"
    })
    public static class AssociatedLiabilities {

        @XmlElement(name = "Liability", required = true)
        protected List<Asset.AssociatedLiabilities.Liability> liability;

        /**
         * Gets the value of the liability property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the liability property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLiability().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Asset.AssociatedLiabilities.Liability }
         * 
         * 
         */
        public List<Asset.AssociatedLiabilities.Liability> getLiability() {
            if (liability == null) {
                liability = new ArrayList<Asset.AssociatedLiabilities.Liability>();
            }
            return this.liability;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Id" type="{http://www.epistandards.com/4.3}Identifier"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id"
        })
        public static class Liability {

            @XmlElement(name = "Id", required = true)
            protected String id;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *         &lt;element name="Frequency" type="{http://www.epistandards.com/4.3}PaymentFrequency"/>
     *         &lt;element name="AnnualEscalation" type="{http://www.epistandards.com/4.3}PositivePercentage" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amount",
        "frequency",
        "annualEscalation"
    })
    public static class Contributions {

        @XmlElement(name = "Amount", required = true)
        protected MonetaryAmount amount;
        @XmlElement(name = "Frequency", required = true)
        protected PaymentFrequency frequency;
        @XmlElement(name = "AnnualEscalation")
        protected BigDecimal annualEscalation;

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setAmount(MonetaryAmount value) {
            this.amount = value;
        }

        /**
         * Gets the value of the frequency property.
         * 
         * @return
         *     possible object is
         *     {@link PaymentFrequency }
         *     
         */
        public PaymentFrequency getFrequency() {
            return frequency;
        }

        /**
         * Sets the value of the frequency property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaymentFrequency }
         *     
         */
        public void setFrequency(PaymentFrequency value) {
            this.frequency = value;
        }

        /**
         * Gets the value of the annualEscalation property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getAnnualEscalation() {
            return annualEscalation;
        }

        /**
         * Sets the value of the annualEscalation property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setAnnualEscalation(BigDecimal value) {
            this.annualEscalation = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DisposalValue" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *         &lt;element name="DisposalDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "disposalValue",
        "disposalDate"
    })
    public static class DisposalDetails {

        @XmlElement(name = "DisposalValue", required = true)
        protected MonetaryAmount disposalValue;
        @XmlElement(name = "DisposalDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar disposalDate;

        /**
         * Gets the value of the disposalValue property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getDisposalValue() {
            return disposalValue;
        }

        /**
         * Sets the value of the disposalValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setDisposalValue(MonetaryAmount value) {
            this.disposalValue = value;
        }

        /**
         * Gets the value of the disposalDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDisposalDate() {
            return disposalDate;
        }

        /**
         * Sets the value of the disposalDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDisposalDate(XMLGregorianCalendar value) {
            this.disposalDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *         &lt;element name="Frequency" type="{http://www.epistandards.com/4.3}PaymentFrequency"/>
     *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="ReinvestIncome" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "amount",
        "frequency",
        "startDate",
        "endDate",
        "reinvestIncome"
    })
    public static class Income {

        @XmlElement(name = "Amount", required = true)
        protected MonetaryAmount amount;
        @XmlElement(name = "Frequency", required = true)
        protected PaymentFrequency frequency;
        @XmlElement(name = "StartDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startDate;
        @XmlElement(name = "EndDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endDate;
        @XmlElement(name = "ReinvestIncome")
        protected boolean reinvestIncome;

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setAmount(MonetaryAmount value) {
            this.amount = value;
        }

        /**
         * Gets the value of the frequency property.
         * 
         * @return
         *     possible object is
         *     {@link PaymentFrequency }
         *     
         */
        public PaymentFrequency getFrequency() {
            return frequency;
        }

        /**
         * Sets the value of the frequency property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaymentFrequency }
         *     
         */
        public void setFrequency(PaymentFrequency value) {
            this.frequency = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartDate(XMLGregorianCalendar value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndDate(XMLGregorianCalendar value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the reinvestIncome property.
         * 
         */
        public boolean isReinvestIncome() {
            return reinvestIncome;
        }

        /**
         * Sets the value of the reinvestIncome property.
         * 
         */
        public void setReinvestIncome(boolean value) {
            this.reinvestIncome = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Note" type="{http://www.epistandards.com/4.3}Note" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "note"
    })
    public static class Notes {

        @XmlElement(name = "Note", required = true)
        protected List<Note> note;

        /**
         * Gets the value of the note property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the note property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Note }
         * 
         * 
         */
        public List<Note> getNote() {
            if (note == null) {
                note = new ArrayList<Note>();
            }
            return this.note;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Owner" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice>
     *                     &lt;element name="ClientId" type="{http://www.epistandards.com/4.3}Identifier"/>
     *                     &lt;element name="AccountID" type="{http://www.epistandards.com/4.3}Identifier"/>
     *                   &lt;/choice>
     *                   &lt;element name="PercentageOfOwnership" type="{http://www.epistandards.com/4.3}PositivePercentage" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "owner"
    })
    public static class Owners {

        @XmlElement(name = "Owner", required = true)
        protected List<Asset.Owners.Owner> owner;

        /**
         * Gets the value of the owner property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the owner property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOwner().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Asset.Owners.Owner }
         * 
         * 
         */
        public List<Asset.Owners.Owner> getOwner() {
            if (owner == null) {
                owner = new ArrayList<Asset.Owners.Owner>();
            }
            return this.owner;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice>
         *           &lt;element name="ClientId" type="{http://www.epistandards.com/4.3}Identifier"/>
         *           &lt;element name="AccountID" type="{http://www.epistandards.com/4.3}Identifier"/>
         *         &lt;/choice>
         *         &lt;element name="PercentageOfOwnership" type="{http://www.epistandards.com/4.3}PositivePercentage" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clientId",
            "accountID",
            "percentageOfOwnership"
        })
        public static class Owner {

            @XmlElement(name = "ClientId")
            protected String clientId;
            @XmlElement(name = "AccountID")
            protected String accountID;
            @XmlElement(name = "PercentageOfOwnership")
            protected BigDecimal percentageOfOwnership;

            /**
             * Gets the value of the clientId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClientId() {
                return clientId;
            }

            /**
             * Sets the value of the clientId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClientId(String value) {
                this.clientId = value;
            }

            /**
             * Gets the value of the accountID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccountID() {
                return accountID;
            }

            /**
             * Sets the value of the accountID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccountID(String value) {
                this.accountID = value;
            }

            /**
             * Gets the value of the percentageOfOwnership property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPercentageOfOwnership() {
                return percentageOfOwnership;
            }

            /**
             * Sets the value of the percentageOfOwnership property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPercentageOfOwnership(BigDecimal value) {
                this.percentageOfOwnership = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PaymentMethod" type="{http://www.epistandards.com/4.3}PaymentMethod"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "paymentMethod"
    })
    public static class Payment {

        @XmlElement(name = "PaymentMethod", required = true)
        protected PaymentMethod paymentMethod;

        /**
         * Gets the value of the paymentMethod property.
         * 
         * @return
         *     possible object is
         *     {@link PaymentMethod }
         *     
         */
        public PaymentMethod getPaymentMethod() {
            return paymentMethod;
        }

        /**
         * Sets the value of the paymentMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link PaymentMethod }
         *     
         */
        public void setPaymentMethod(PaymentMethod value) {
            this.paymentMethod = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TitleType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Community"/>
     *               &lt;enumeration value="Unit"/>
     *               &lt;enumeration value="Strata"/>
     *               &lt;enumeration value="Stratum"/>
     *               &lt;enumeration value="Company"/>
     *               &lt;enumeration value="CrownLand"/>
     *               &lt;enumeration value="CrownLease"/>
     *               &lt;enumeration value="Freehold"/>
     *               &lt;enumeration value="GroupTitlesPlan"/>
     *               &lt;enumeration value="Leasehold"/>
     *               &lt;enumeration value="Moiety"/>
     *               &lt;enumeration value="Purple"/>
     *               &lt;enumeration value="Other"/>
     *               &lt;enumeration value="None"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PropertyType" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="100"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ZoningType" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="100"/>
     *               &lt;enumeration value="Residential"/>
     *               &lt;enumeration value="Commercial"/>
     *               &lt;enumeration value="CommercialResidential"/>
     *               &lt;enumeration value="Rural"/>
     *               &lt;enumeration value="RuralResidential"/>
     *               &lt;enumeration value="ShortStayAccommodation"/>
     *               &lt;enumeration value="Urban"/>
     *               &lt;enumeration value="Other"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Address" type="{http://www.epistandards.com/4.3}Address"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titleType",
        "propertyType",
        "zoningType",
        "address"
    })
    public static class RealEstate {

        @XmlElement(name = "TitleType", required = true)
        protected String titleType;
        @XmlElement(name = "PropertyType")
        protected String propertyType;
        @XmlElement(name = "ZoningType")
        protected String zoningType;
        @XmlElement(name = "Address", required = true)
        protected Address address;

        /**
         * Gets the value of the titleType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitleType() {
            return titleType;
        }

        /**
         * Sets the value of the titleType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitleType(String value) {
            this.titleType = value;
        }

        /**
         * Gets the value of the propertyType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPropertyType() {
            return propertyType;
        }

        /**
         * Sets the value of the propertyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPropertyType(String value) {
            this.propertyType = value;
        }

        /**
         * Gets the value of the zoningType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZoningType() {
            return zoningType;
        }

        /**
         * Sets the value of the zoningType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZoningType(String value) {
            this.zoningType = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link Address }
         *     
         */
        public Address getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link Address }
         *     
         */
        public void setAddress(Address value) {
            this.address = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CurrentValue" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *         &lt;element name="ValuationType" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Market"/>
     *               &lt;enumeration value="Government"/>
     *               &lt;enumeration value="Estimate"/>
     *               &lt;enumeration value="Other"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ValuationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="MaturityValue" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
     *         &lt;element name="MaturityDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="CapitalValue" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "currentValue",
        "valuationType",
        "valuationDate",
        "maturityValue",
        "maturityDate",
        "capitalValue"
    })
    public static class ValuationDetails {

        @XmlElement(name = "CurrentValue", required = true)
        protected MonetaryAmount currentValue;
        @XmlElement(name = "ValuationType")
        protected String valuationType;
        @XmlElement(name = "ValuationDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar valuationDate;
        @XmlElement(name = "MaturityValue")
        protected MonetaryAmount maturityValue;
        @XmlElement(name = "MaturityDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar maturityDate;
        @XmlElement(name = "CapitalValue")
        protected MonetaryAmount capitalValue;

        /**
         * Gets the value of the currentValue property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getCurrentValue() {
            return currentValue;
        }

        /**
         * Sets the value of the currentValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setCurrentValue(MonetaryAmount value) {
            this.currentValue = value;
        }

        /**
         * Gets the value of the valuationType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValuationType() {
            return valuationType;
        }

        /**
         * Sets the value of the valuationType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValuationType(String value) {
            this.valuationType = value;
        }

        /**
         * Gets the value of the valuationDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValuationDate() {
            return valuationDate;
        }

        /**
         * Sets the value of the valuationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValuationDate(XMLGregorianCalendar value) {
            this.valuationDate = value;
        }

        /**
         * Gets the value of the maturityValue property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getMaturityValue() {
            return maturityValue;
        }

        /**
         * Sets the value of the maturityValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setMaturityValue(MonetaryAmount value) {
            this.maturityValue = value;
        }

        /**
         * Gets the value of the maturityDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getMaturityDate() {
            return maturityDate;
        }

        /**
         * Sets the value of the maturityDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setMaturityDate(XMLGregorianCalendar value) {
            this.maturityDate = value;
        }

        /**
         * Gets the value of the capitalValue property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getCapitalValue() {
            return capitalValue;
        }

        /**
         * Sets the value of the capitalValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setCapitalValue(MonetaryAmount value) {
            this.capitalValue = value;
        }

    }

}
