//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssetType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LSAN"/>
 *     &lt;enumeration value="LSAW"/>
 *     &lt;enumeration value="LSHC"/>
 *     &lt;enumeration value="LSMV"/>
 *     &lt;enumeration value="LSJE"/>
 *     &lt;enumeration value="LSPR"/>
 *     &lt;enumeration value="LSOT"/>
 *     &lt;enumeration value="INOT"/>
 *     &lt;enumeration value="BAPM"/>
 *     &lt;enumeration value="BAAR"/>
 *     &lt;enumeration value="BAIN"/>
 *     &lt;enumeration value="BAPE"/>
 *     &lt;enumeration value="BAPC"/>
 *     &lt;enumeration value="BAGW"/>
 *     &lt;enumeration value="BAFR"/>
 *     &lt;enumeration value="LACH"/>
 *     &lt;enumeration value="LACS"/>
 *     &lt;enumeration value="LAFD"/>
 *     &lt;enumeration value="REPR"/>
 *     &lt;enumeration value="REIP"/>
 *     &lt;enumeration value="REHR"/>
 *     &lt;enumeration value="RESR"/>
 *     &lt;enumeration value="RECR"/>
 *     &lt;enumeration value="RTOT"/>
 *     &lt;enumeration value="BISP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AssetType")
@XmlEnum
public enum AssetType {


    /**
     * Life Style - Antiques
     * 
     */
    LSAN,

    /**
     * Life Style - Artwork
     * 
     */
    LSAW,

    /**
     * Life Style - Household Contents
     * 
     */
    LSHC,

    /**
     * Life Style - Motor Vehicle
     * 
     */
    LSMV,

    /**
     * Life Style - Jewellery
     * 
     */
    LSJE,

    /**
     * Life Style - Primary Residence
     * 
     */
    LSPR,

    /**
     * Life Style - Other
     * 
     */
    LSOT,

    /**
     * Investments - Other
     * 
     */
    INOT,

    /**
     * Business Assets - Plant and Machinery
     * 
     */
    BAPM,

    /**
     * Business Assets - Accounts Receivable
     * 
     */
    BAAR,

    /**
     * Business Assets - Inventory
     * 
     */
    BAIN,

    /**
     * Business Assets - Prepaid Expenses
     * 
     */
    BAPE,

    /**
     * Business Assets - Patents and Copyrights
     * 
     */
    BAPC,

    /**
     * Business Assets - Goodwill
     * 
     */
    BAGW,

    /**
     * Business Assets - Franchises
     * 
     */
    BAFR,

    /**
     * Liquid Assets - Cash on Hand
     * 
     */
    LACH,

    /**
     * Liquid Assets - Cash Savings
     * 
     */
    LACS,

    /**
     * Liquid Assets - Fixed Deposits
     * 
     */
    LAFD,

    /**
     * Real Estate - Primary Residence
     * 
     */
    REPR,

    /**
     * Real Estate - Investment Property
     * 
     */
    REIP,

    /**
     * Property - Holiday Residence
     * 
     */
    REHR,

    /**
     * Property - Second Residence
     * 
     */
    RESR,

    /**
     * Property - Commerical Property
     * 
     */
    RECR,

    /**
     * Retirement - Other
     * 
     */
    RTOT,

    /**
     * Business Interests - Sole Proprieter
     * 
     */
    BISP;

    public String value() {
        return name();
    }

    public static AssetType fromValue(String v) {
        return valueOf(v);
    }

}
