//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BeneficiaryAnnuity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryAnnuity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Id" type="{http://www.epistandards.com/4.3}Identifier"/>
 *           &lt;choice>
 *             &lt;element name="Person" type="{http://www.epistandards.com/4.3}EntityPersonShort"/>
 *             &lt;element name="Organisation" type="{http://www.epistandards.com/4.3}EntityOrganisation"/>
 *             &lt;element name="Trust" type="{http://www.epistandards.com/4.3}EntityTrust"/>
 *             &lt;element name="Superfund" type="{http://www.epistandards.com/4.3}EntitySuperfund"/>
 *             &lt;element name="MyEstate">
 *               &lt;complexType>
 *                 &lt;complexContent>
 *                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                     &lt;sequence>
 *                       &lt;element name="EstateName">
 *                         &lt;simpleType>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                             &lt;minLength value="1"/>
 *                             &lt;maxLength value="200"/>
 *                           &lt;/restriction>
 *                         &lt;/simpleType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                   &lt;/restriction>
 *                 &lt;/complexContent>
 *               &lt;/complexType>
 *             &lt;/element>
 *           &lt;/choice>
 *         &lt;/choice>
 *         &lt;element name="FPSId" type="{http://www.epistandards.com/4.3}Identifier" minOccurs="0"/>
 *         &lt;element name="PortionOfBenefit" type="{http://www.epistandards.com/4.3}PositivePercentage" minOccurs="0"/>
 *         &lt;element name="BeneficiaryType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Nominated"/>
 *               &lt;enumeration value="Reversionary"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiaryAnnuity", propOrder = {
    "id",
    "person",
    "organisation",
    "trust",
    "superfund",
    "myEstate",
    "fpsId",
    "portionOfBenefit",
    "beneficiaryType",
    "epiExtension"
})
public class BeneficiaryAnnuity {

    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Person")
    protected EntityPersonShort person;
    @XmlElement(name = "Organisation")
    protected EntityOrganisation organisation;
    @XmlElement(name = "Trust")
    protected EntityTrust trust;
    @XmlElement(name = "Superfund")
    protected EntitySuperfund superfund;
    @XmlElement(name = "MyEstate")
    protected BeneficiaryAnnuity.MyEstate myEstate;
    @XmlElement(name = "FPSId")
    protected String fpsId;
    @XmlElement(name = "PortionOfBenefit")
    protected BigDecimal portionOfBenefit;
    @XmlElement(name = "BeneficiaryType")
    protected String beneficiaryType;
    @XmlElement(name = "EPIExtension")
    protected EPIExtension epiExtension;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link EntityPersonShort }
     *     
     */
    public EntityPersonShort getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityPersonShort }
     *     
     */
    public void setPerson(EntityPersonShort value) {
        this.person = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link EntityOrganisation }
     *     
     */
    public EntityOrganisation getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityOrganisation }
     *     
     */
    public void setOrganisation(EntityOrganisation value) {
        this.organisation = value;
    }

    /**
     * Gets the value of the trust property.
     * 
     * @return
     *     possible object is
     *     {@link EntityTrust }
     *     
     */
    public EntityTrust getTrust() {
        return trust;
    }

    /**
     * Sets the value of the trust property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityTrust }
     *     
     */
    public void setTrust(EntityTrust value) {
        this.trust = value;
    }

    /**
     * Gets the value of the superfund property.
     * 
     * @return
     *     possible object is
     *     {@link EntitySuperfund }
     *     
     */
    public EntitySuperfund getSuperfund() {
        return superfund;
    }

    /**
     * Sets the value of the superfund property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntitySuperfund }
     *     
     */
    public void setSuperfund(EntitySuperfund value) {
        this.superfund = value;
    }

    /**
     * Gets the value of the myEstate property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryAnnuity.MyEstate }
     *     
     */
    public BeneficiaryAnnuity.MyEstate getMyEstate() {
        return myEstate;
    }

    /**
     * Sets the value of the myEstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryAnnuity.MyEstate }
     *     
     */
    public void setMyEstate(BeneficiaryAnnuity.MyEstate value) {
        this.myEstate = value;
    }

    /**
     * Gets the value of the fpsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPSId() {
        return fpsId;
    }

    /**
     * Sets the value of the fpsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPSId(String value) {
        this.fpsId = value;
    }

    /**
     * Gets the value of the portionOfBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortionOfBenefit() {
        return portionOfBenefit;
    }

    /**
     * Sets the value of the portionOfBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortionOfBenefit(BigDecimal value) {
        this.portionOfBenefit = value;
    }

    /**
     * Gets the value of the beneficiaryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneficiaryType() {
        return beneficiaryType;
    }

    /**
     * Sets the value of the beneficiaryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneficiaryType(String value) {
        this.beneficiaryType = value;
    }

    /**
     * Gets the value of the epiExtension property.
     * 
     * @return
     *     possible object is
     *     {@link EPIExtension }
     *     
     */
    public EPIExtension getEPIExtension() {
        return epiExtension;
    }

    /**
     * Sets the value of the epiExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPIExtension }
     *     
     */
    public void setEPIExtension(EPIExtension value) {
        this.epiExtension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EstateName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="200"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "estateName"
    })
    public static class MyEstate {

        @XmlElement(name = "EstateName", required = true)
        protected String estateName;

        /**
         * Gets the value of the estateName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstateName() {
            return estateName;
        }

        /**
         * Sets the value of the estateName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstateName(String value) {
            this.estateName = value;
        }

    }

}
