//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BeneficiaryRisk complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BeneficiaryRisk">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ClientId" type="{http://www.epistandards.com/4.3}Identifier"/>
 *           &lt;element name="AccountId" type="{http://www.epistandards.com/4.3}Identifier"/>
 *           &lt;choice>
 *             &lt;element name="Person" type="{http://www.epistandards.com/4.3}EntityPersonShort"/>
 *             &lt;element name="Organisation" type="{http://www.epistandards.com/4.3}EntityOrganisation"/>
 *             &lt;element name="Trust" type="{http://www.epistandards.com/4.3}EntityTrust"/>
 *             &lt;element name="Superfund" type="{http://www.epistandards.com/4.3}EntitySuperfund"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *         &lt;element name="FPSId" type="{http://www.epistandards.com/4.3}Identifier" minOccurs="0"/>
 *         &lt;element name="RelationshipToLifeAssured" type="{http://www.epistandards.com/4.3}LifeAssuredRelationship" minOccurs="0"/>
 *         &lt;element name="PortionOfBenefit" type="{http://www.epistandards.com/4.3}PositivePercentage" minOccurs="0"/>
 *         &lt;element name="BeneficiaryType" type="{http://www.epistandards.com/4.3}BeneficiaryType" minOccurs="0"/>
 *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BeneficiaryRisk", propOrder = {
    "clientId",
    "accountId",
    "person",
    "organisation",
    "trust",
    "superfund",
    "fpsId",
    "relationshipToLifeAssured",
    "portionOfBenefit",
    "beneficiaryType",
    "epiExtension"
})
public class BeneficiaryRisk {

    @XmlElement(name = "ClientId")
    protected String clientId;
    @XmlElement(name = "AccountId")
    protected String accountId;
    @XmlElement(name = "Person")
    protected EntityPersonShort person;
    @XmlElement(name = "Organisation")
    protected EntityOrganisation organisation;
    @XmlElement(name = "Trust")
    protected EntityTrust trust;
    @XmlElement(name = "Superfund")
    protected EntitySuperfund superfund;
    @XmlElement(name = "FPSId")
    protected String fpsId;
    @XmlElement(name = "RelationshipToLifeAssured")
    protected LifeAssuredRelationship relationshipToLifeAssured;
    @XmlElement(name = "PortionOfBenefit")
    protected BigDecimal portionOfBenefit;
    @XmlElement(name = "BeneficiaryType")
    protected BeneficiaryType beneficiaryType;
    @XmlElement(name = "EPIExtension")
    protected EPIExtension epiExtension;

    /**
     * Gets the value of the clientId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * Sets the value of the clientId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientId(String value) {
        this.clientId = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountId(String value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link EntityPersonShort }
     *     
     */
    public EntityPersonShort getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityPersonShort }
     *     
     */
    public void setPerson(EntityPersonShort value) {
        this.person = value;
    }

    /**
     * Gets the value of the organisation property.
     * 
     * @return
     *     possible object is
     *     {@link EntityOrganisation }
     *     
     */
    public EntityOrganisation getOrganisation() {
        return organisation;
    }

    /**
     * Sets the value of the organisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityOrganisation }
     *     
     */
    public void setOrganisation(EntityOrganisation value) {
        this.organisation = value;
    }

    /**
     * Gets the value of the trust property.
     * 
     * @return
     *     possible object is
     *     {@link EntityTrust }
     *     
     */
    public EntityTrust getTrust() {
        return trust;
    }

    /**
     * Sets the value of the trust property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityTrust }
     *     
     */
    public void setTrust(EntityTrust value) {
        this.trust = value;
    }

    /**
     * Gets the value of the superfund property.
     * 
     * @return
     *     possible object is
     *     {@link EntitySuperfund }
     *     
     */
    public EntitySuperfund getSuperfund() {
        return superfund;
    }

    /**
     * Sets the value of the superfund property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntitySuperfund }
     *     
     */
    public void setSuperfund(EntitySuperfund value) {
        this.superfund = value;
    }

    /**
     * Gets the value of the fpsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFPSId() {
        return fpsId;
    }

    /**
     * Sets the value of the fpsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFPSId(String value) {
        this.fpsId = value;
    }

    /**
     * Gets the value of the relationshipToLifeAssured property.
     * 
     * @return
     *     possible object is
     *     {@link LifeAssuredRelationship }
     *     
     */
    public LifeAssuredRelationship getRelationshipToLifeAssured() {
        return relationshipToLifeAssured;
    }

    /**
     * Sets the value of the relationshipToLifeAssured property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifeAssuredRelationship }
     *     
     */
    public void setRelationshipToLifeAssured(LifeAssuredRelationship value) {
        this.relationshipToLifeAssured = value;
    }

    /**
     * Gets the value of the portionOfBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPortionOfBenefit() {
        return portionOfBenefit;
    }

    /**
     * Sets the value of the portionOfBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPortionOfBenefit(BigDecimal value) {
        this.portionOfBenefit = value;
    }

    /**
     * Gets the value of the beneficiaryType property.
     * 
     * @return
     *     possible object is
     *     {@link BeneficiaryType }
     *     
     */
    public BeneficiaryType getBeneficiaryType() {
        return beneficiaryType;
    }

    /**
     * Sets the value of the beneficiaryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneficiaryType }
     *     
     */
    public void setBeneficiaryType(BeneficiaryType value) {
        this.beneficiaryType = value;
    }

    /**
     * Gets the value of the epiExtension property.
     * 
     * @return
     *     possible object is
     *     {@link EPIExtension }
     *     
     */
    public EPIExtension getEPIExtension() {
        return epiExtension;
    }

    /**
     * Sets the value of the epiExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPIExtension }
     *     
     */
    public void setEPIExtension(EPIExtension value) {
        this.epiExtension = value;
    }

}
