//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactMethod.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContactMethod">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Address"/>
 *     &lt;enumeration value="Phone"/>
 *     &lt;enumeration value="Email"/>
 *     &lt;enumeration value="Web"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ContactMethod")
@XmlEnum
public enum ContactMethod {

    @XmlEnumValue("Address")
    ADDRESS("Address"),
    @XmlEnumValue("Phone")
    PHONE("Phone"),
    @XmlEnumValue("Email")
    EMAIL("Email"),
    @XmlEnumValue("Web")
    WEB("Web"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    ContactMethod(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContactMethod fromValue(String v) {
        for (ContactMethod c: ContactMethod.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
