//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Indicates whether cover escalates by CPI or by a fixed amount
 * 
 * <p>Java class for EscalationMethod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EscalationMethod">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="AsCPI">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FixedAmountAsPercentage" type="{http://www.epistandards.com/4.3}Percentage"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EscalationMethod", propOrder = {
    "asCPI",
    "fixedAmountAsPercentage"
})
public class EscalationMethod {

    @XmlElement(name = "AsCPI")
    protected String asCPI;
    @XmlElement(name = "FixedAmountAsPercentage")
    protected BigDecimal fixedAmountAsPercentage;

    /**
     * Gets the value of the asCPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsCPI() {
        return asCPI;
    }

    /**
     * Sets the value of the asCPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsCPI(String value) {
        this.asCPI = value;
    }

    /**
     * Gets the value of the fixedAmountAsPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFixedAmountAsPercentage() {
        return fixedAmountAsPercentage;
    }

    /**
     * Sets the value of the fixedAmountAsPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFixedAmountAsPercentage(BigDecimal value) {
        this.fixedAmountAsPercentage = value;
    }

}
