//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncomeTaxCredits complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IncomeTaxCredits">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Imputation" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="DomesticOther" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="ForeignOther" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="ForeignDividend" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="ForeignPassiveIncome" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="ForeignInterest" type="{http://www.epistandards.com/4.3}MonetaryAmount" minOccurs="0"/>
 *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IncomeTaxCredits", propOrder = {
    "imputation",
    "domesticOther",
    "foreignOther",
    "foreignDividend",
    "foreignPassiveIncome",
    "foreignInterest",
    "epiExtension"
})
public class IncomeTaxCredits {

    @XmlElement(name = "Imputation")
    protected MonetaryAmount imputation;
    @XmlElement(name = "DomesticOther")
    protected MonetaryAmount domesticOther;
    @XmlElement(name = "ForeignOther")
    protected MonetaryAmount foreignOther;
    @XmlElement(name = "ForeignDividend")
    protected MonetaryAmount foreignDividend;
    @XmlElement(name = "ForeignPassiveIncome")
    protected MonetaryAmount foreignPassiveIncome;
    @XmlElement(name = "ForeignInterest")
    protected MonetaryAmount foreignInterest;
    @XmlElement(name = "EPIExtension")
    protected EPIExtension epiExtension;

    /**
     * Gets the value of the imputation property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getImputation() {
        return imputation;
    }

    /**
     * Sets the value of the imputation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setImputation(MonetaryAmount value) {
        this.imputation = value;
    }

    /**
     * Gets the value of the domesticOther property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getDomesticOther() {
        return domesticOther;
    }

    /**
     * Sets the value of the domesticOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setDomesticOther(MonetaryAmount value) {
        this.domesticOther = value;
    }

    /**
     * Gets the value of the foreignOther property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getForeignOther() {
        return foreignOther;
    }

    /**
     * Sets the value of the foreignOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setForeignOther(MonetaryAmount value) {
        this.foreignOther = value;
    }

    /**
     * Gets the value of the foreignDividend property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getForeignDividend() {
        return foreignDividend;
    }

    /**
     * Sets the value of the foreignDividend property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setForeignDividend(MonetaryAmount value) {
        this.foreignDividend = value;
    }

    /**
     * Gets the value of the foreignPassiveIncome property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getForeignPassiveIncome() {
        return foreignPassiveIncome;
    }

    /**
     * Sets the value of the foreignPassiveIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setForeignPassiveIncome(MonetaryAmount value) {
        this.foreignPassiveIncome = value;
    }

    /**
     * Gets the value of the foreignInterest property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getForeignInterest() {
        return foreignInterest;
    }

    /**
     * Sets the value of the foreignInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setForeignInterest(MonetaryAmount value) {
        this.foreignInterest = value;
    }

    /**
     * Gets the value of the epiExtension property.
     * 
     * @return
     *     possible object is
     *     {@link EPIExtension }
     *     
     */
    public EPIExtension getEPIExtension() {
        return epiExtension;
    }

    /**
     * Sets the value of the epiExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPIExtension }
     *     
     */
    public void setEPIExtension(EPIExtension value) {
        this.epiExtension = value;
    }

}
