//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Industry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Industry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PrimaryIndustry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="13"/>
 *               &lt;enumeration value="14"/>
 *               &lt;enumeration value="15"/>
 *               &lt;enumeration value="16"/>
 *               &lt;enumeration value="21"/>
 *               &lt;enumeration value="22"/>
 *               &lt;enumeration value="30"/>
 *               &lt;enumeration value="41"/>
 *               &lt;enumeration value="42"/>
 *               &lt;enumeration value="110"/>
 *               &lt;enumeration value="120"/>
 *               &lt;enumeration value="131"/>
 *               &lt;enumeration value="141"/>
 *               &lt;enumeration value="142"/>
 *               &lt;enumeration value="151"/>
 *               &lt;enumeration value="152"/>
 *               &lt;enumeration value="211"/>
 *               &lt;enumeration value="212"/>
 *               &lt;enumeration value="213"/>
 *               &lt;enumeration value="214"/>
 *               &lt;enumeration value="215"/>
 *               &lt;enumeration value="216"/>
 *               &lt;enumeration value="217"/>
 *               &lt;enumeration value="218"/>
 *               &lt;enumeration value="219"/>
 *               &lt;enumeration value="221"/>
 *               &lt;enumeration value="222"/>
 *               &lt;enumeration value="223"/>
 *               &lt;enumeration value="224"/>
 *               &lt;enumeration value="225"/>
 *               &lt;enumeration value="226"/>
 *               &lt;enumeration value="231"/>
 *               &lt;enumeration value="232"/>
 *               &lt;enumeration value="233"/>
 *               &lt;enumeration value="241"/>
 *               &lt;enumeration value="242"/>
 *               &lt;enumeration value="243"/>
 *               &lt;enumeration value="251"/>
 *               &lt;enumeration value="252"/>
 *               &lt;enumeration value="253"/>
 *               &lt;enumeration value="254"/>
 *               &lt;enumeration value="255"/>
 *               &lt;enumeration value="256"/>
 *               &lt;enumeration value="261"/>
 *               &lt;enumeration value="262"/>
 *               &lt;enumeration value="263"/>
 *               &lt;enumeration value="264"/>
 *               &lt;enumeration value="271"/>
 *               &lt;enumeration value="272"/>
 *               &lt;enumeration value="273"/>
 *               &lt;enumeration value="274"/>
 *               &lt;enumeration value="275"/>
 *               &lt;enumeration value="276"/>
 *               &lt;enumeration value="281"/>
 *               &lt;enumeration value="282"/>
 *               &lt;enumeration value="283"/>
 *               &lt;enumeration value="284"/>
 *               &lt;enumeration value="285"/>
 *               &lt;enumeration value="286"/>
 *               &lt;enumeration value="291"/>
 *               &lt;enumeration value="292"/>
 *               &lt;enumeration value="294"/>
 *               &lt;enumeration value="361"/>
 *               &lt;enumeration value="362"/>
 *               &lt;enumeration value="370"/>
 *               &lt;enumeration value="411"/>
 *               &lt;enumeration value="412"/>
 *               &lt;enumeration value="421"/>
 *               &lt;enumeration value="422"/>
 *               &lt;enumeration value="423"/>
 *               &lt;enumeration value="424"/>
 *               &lt;enumeration value="425"/>
 *               &lt;enumeration value="451"/>
 *               &lt;enumeration value="452"/>
 *               &lt;enumeration value="453"/>
 *               &lt;enumeration value="461"/>
 *               &lt;enumeration value="462"/>
 *               &lt;enumeration value="471"/>
 *               &lt;enumeration value="472"/>
 *               &lt;enumeration value="473"/>
 *               &lt;enumeration value="479"/>
 *               &lt;enumeration value="511"/>
 *               &lt;enumeration value="512"/>
 *               &lt;enumeration value="521"/>
 *               &lt;enumeration value="522"/>
 *               &lt;enumeration value="523"/>
 *               &lt;enumeration value="524"/>
 *               &lt;enumeration value="525"/>
 *               &lt;enumeration value="526"/>
 *               &lt;enumeration value="531"/>
 *               &lt;enumeration value="532"/>
 *               &lt;enumeration value="571"/>
 *               &lt;enumeration value="572"/>
 *               &lt;enumeration value="573"/>
 *               &lt;enumeration value="574"/>
 *               &lt;enumeration value="611"/>
 *               &lt;enumeration value="612"/>
 *               &lt;enumeration value="620"/>
 *               &lt;enumeration value="630"/>
 *               &lt;enumeration value="640"/>
 *               &lt;enumeration value="650"/>
 *               &lt;enumeration value="661"/>
 *               &lt;enumeration value="662"/>
 *               &lt;enumeration value="663"/>
 *               &lt;enumeration value="664"/>
 *               &lt;enumeration value="670"/>
 *               &lt;enumeration value="711"/>
 *               &lt;enumeration value="712"/>
 *               &lt;enumeration value="731"/>
 *               &lt;enumeration value="732"/>
 *               &lt;enumeration value="733"/>
 *               &lt;enumeration value="734"/>
 *               &lt;enumeration value="741"/>
 *               &lt;enumeration value="742"/>
 *               &lt;enumeration value="751"/>
 *               &lt;enumeration value="752"/>
 *               &lt;enumeration value="771"/>
 *               &lt;enumeration value="772"/>
 *               &lt;enumeration value="773"/>
 *               &lt;enumeration value="774"/>
 *               &lt;enumeration value="781"/>
 *               &lt;enumeration value="782"/>
 *               &lt;enumeration value="783"/>
 *               &lt;enumeration value="784"/>
 *               &lt;enumeration value="785"/>
 *               &lt;enumeration value="786"/>
 *               &lt;enumeration value="811"/>
 *               &lt;enumeration value="812"/>
 *               &lt;enumeration value="813"/>
 *               &lt;enumeration value="820"/>
 *               &lt;enumeration value="841"/>
 *               &lt;enumeration value="842"/>
 *               &lt;enumeration value="843"/>
 *               &lt;enumeration value="844"/>
 *               &lt;enumeration value="861"/>
 *               &lt;enumeration value="862"/>
 *               &lt;enumeration value="863"/>
 *               &lt;enumeration value="864"/>
 *               &lt;enumeration value="871"/>
 *               &lt;enumeration value="872"/>
 *               &lt;enumeration value="911"/>
 *               &lt;enumeration value="912"/>
 *               &lt;enumeration value="921"/>
 *               &lt;enumeration value="922"/>
 *               &lt;enumeration value="923"/>
 *               &lt;enumeration value="924"/>
 *               &lt;enumeration value="925"/>
 *               &lt;enumeration value="931"/>
 *               &lt;enumeration value="932"/>
 *               &lt;enumeration value="933"/>
 *               &lt;enumeration value="951"/>
 *               &lt;enumeration value="952"/>
 *               &lt;enumeration value="961"/>
 *               &lt;enumeration value="962"/>
 *               &lt;enumeration value="963"/>
 *               &lt;enumeration value="970"/>
 *               &lt;enumeration value="990"/>
 *               &lt;enumeration value="UNK"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubIndustry">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="111"/>
 *               &lt;enumeration value="112"/>
 *               &lt;enumeration value="113"/>
 *               &lt;enumeration value="114"/>
 *               &lt;enumeration value="115"/>
 *               &lt;enumeration value="116"/>
 *               &lt;enumeration value="117"/>
 *               &lt;enumeration value="119"/>
 *               &lt;enumeration value="121"/>
 *               &lt;enumeration value="122"/>
 *               &lt;enumeration value="123"/>
 *               &lt;enumeration value="124"/>
 *               &lt;enumeration value="125"/>
 *               &lt;enumeration value="130"/>
 *               &lt;enumeration value="141"/>
 *               &lt;enumeration value="142"/>
 *               &lt;enumeration value="151"/>
 *               &lt;enumeration value="152"/>
 *               &lt;enumeration value="153"/>
 *               &lt;enumeration value="159"/>
 *               &lt;enumeration value="161"/>
 *               &lt;enumeration value="162"/>
 *               &lt;enumeration value="169"/>
 *               &lt;enumeration value="211"/>
 *               &lt;enumeration value="212"/>
 *               &lt;enumeration value="213"/>
 *               &lt;enumeration value="219"/>
 *               &lt;enumeration value="220"/>
 *               &lt;enumeration value="301"/>
 *               &lt;enumeration value="302"/>
 *               &lt;enumeration value="303"/>
 *               &lt;enumeration value="411"/>
 *               &lt;enumeration value="412"/>
 *               &lt;enumeration value="413"/>
 *               &lt;enumeration value="414"/>
 *               &lt;enumeration value="415"/>
 *               &lt;enumeration value="419"/>
 *               &lt;enumeration value="420"/>
 *               &lt;enumeration value="1101"/>
 *               &lt;enumeration value="1102"/>
 *               &lt;enumeration value="1200"/>
 *               &lt;enumeration value="1311"/>
 *               &lt;enumeration value="1312"/>
 *               &lt;enumeration value="1313"/>
 *               &lt;enumeration value="1314"/>
 *               &lt;enumeration value="1315"/>
 *               &lt;enumeration value="1316"/>
 *               &lt;enumeration value="1317"/>
 *               &lt;enumeration value="1319"/>
 *               &lt;enumeration value="1411"/>
 *               &lt;enumeration value="1419"/>
 *               &lt;enumeration value="1420"/>
 *               &lt;enumeration value="1511"/>
 *               &lt;enumeration value="1512"/>
 *               &lt;enumeration value="1513"/>
 *               &lt;enumeration value="1514"/>
 *               &lt;enumeration value="1520"/>
 *               &lt;enumeration value="2111"/>
 *               &lt;enumeration value="2112"/>
 *               &lt;enumeration value="2113"/>
 *               &lt;enumeration value="2121"/>
 *               &lt;enumeration value="2122"/>
 *               &lt;enumeration value="2129"/>
 *               &lt;enumeration value="2130"/>
 *               &lt;enumeration value="2140"/>
 *               &lt;enumeration value="2151"/>
 *               &lt;enumeration value="2152"/>
 *               &lt;enumeration value="2161"/>
 *               &lt;enumeration value="2162"/>
 *               &lt;enumeration value="2163"/>
 *               &lt;enumeration value="2171"/>
 *               &lt;enumeration value="2172"/>
 *               &lt;enumeration value="2173"/>
 *               &lt;enumeration value="2174"/>
 *               &lt;enumeration value="2179"/>
 *               &lt;enumeration value="2181"/>
 *               &lt;enumeration value="2182"/>
 *               &lt;enumeration value="2183"/>
 *               &lt;enumeration value="2184"/>
 *               &lt;enumeration value="2190"/>
 *               &lt;enumeration value="2211"/>
 *               &lt;enumeration value="2212"/>
 *               &lt;enumeration value="2213"/>
 *               &lt;enumeration value="2214"/>
 *               &lt;enumeration value="2215"/>
 *               &lt;enumeration value="2221"/>
 *               &lt;enumeration value="2222"/>
 *               &lt;enumeration value="2223"/>
 *               &lt;enumeration value="2229"/>
 *               &lt;enumeration value="2231"/>
 *               &lt;enumeration value="2232"/>
 *               &lt;enumeration value="2239"/>
 *               &lt;enumeration value="2241"/>
 *               &lt;enumeration value="2242"/>
 *               &lt;enumeration value="2243"/>
 *               &lt;enumeration value="2249"/>
 *               &lt;enumeration value="2250"/>
 *               &lt;enumeration value="2261"/>
 *               &lt;enumeration value="2262"/>
 *               &lt;enumeration value="2311"/>
 *               &lt;enumeration value="2312"/>
 *               &lt;enumeration value="2313"/>
 *               &lt;enumeration value="2321"/>
 *               &lt;enumeration value="2322"/>
 *               &lt;enumeration value="2323"/>
 *               &lt;enumeration value="2329"/>
 *               &lt;enumeration value="2331"/>
 *               &lt;enumeration value="2332"/>
 *               &lt;enumeration value="2333"/>
 *               &lt;enumeration value="2334"/>
 *               &lt;enumeration value="2339"/>
 *               &lt;enumeration value="2411"/>
 *               &lt;enumeration value="2412"/>
 *               &lt;enumeration value="2413"/>
 *               &lt;enumeration value="2421"/>
 *               &lt;enumeration value="2422"/>
 *               &lt;enumeration value="2423"/>
 *               &lt;enumeration value="2430"/>
 *               &lt;enumeration value="2510"/>
 *               &lt;enumeration value="2520"/>
 *               &lt;enumeration value="2531"/>
 *               &lt;enumeration value="2532"/>
 *               &lt;enumeration value="2533"/>
 *               &lt;enumeration value="2534"/>
 *               &lt;enumeration value="2535"/>
 *               &lt;enumeration value="2541"/>
 *               &lt;enumeration value="2542"/>
 *               &lt;enumeration value="2543"/>
 *               &lt;enumeration value="2544"/>
 *               &lt;enumeration value="2545"/>
 *               &lt;enumeration value="2546"/>
 *               &lt;enumeration value="2547"/>
 *               &lt;enumeration value="2549"/>
 *               &lt;enumeration value="2551"/>
 *               &lt;enumeration value="2559"/>
 *               &lt;enumeration value="2561"/>
 *               &lt;enumeration value="2562"/>
 *               &lt;enumeration value="2563"/>
 *               &lt;enumeration value="2564"/>
 *               &lt;enumeration value="2565"/>
 *               &lt;enumeration value="2566"/>
 *               &lt;enumeration value="2610"/>
 *               &lt;enumeration value="2621"/>
 *               &lt;enumeration value="2622"/>
 *               &lt;enumeration value="2623"/>
 *               &lt;enumeration value="2629"/>
 *               &lt;enumeration value="2631"/>
 *               &lt;enumeration value="2633"/>
 *               &lt;enumeration value="2634"/>
 *               &lt;enumeration value="2635"/>
 *               &lt;enumeration value="2640"/>
 *               &lt;enumeration value="2711"/>
 *               &lt;enumeration value="2712"/>
 *               &lt;enumeration value="2713"/>
 *               &lt;enumeration value="2721"/>
 *               &lt;enumeration value="2722"/>
 *               &lt;enumeration value="2723"/>
 *               &lt;enumeration value="2729"/>
 *               &lt;enumeration value="2731"/>
 *               &lt;enumeration value="2732"/>
 *               &lt;enumeration value="2733"/>
 *               &lt;enumeration value="2741"/>
 *               &lt;enumeration value="2742"/>
 *               &lt;enumeration value="2749"/>
 *               &lt;enumeration value="2751"/>
 *               &lt;enumeration value="2759"/>
 *               &lt;enumeration value="2761"/>
 *               &lt;enumeration value="2762"/>
 *               &lt;enumeration value="2763"/>
 *               &lt;enumeration value="2764"/>
 *               &lt;enumeration value="2765"/>
 *               &lt;enumeration value="2769"/>
 *               &lt;enumeration value="2811"/>
 *               &lt;enumeration value="2812"/>
 *               &lt;enumeration value="2813"/>
 *               &lt;enumeration value="2819"/>
 *               &lt;enumeration value="2821"/>
 *               &lt;enumeration value="2822"/>
 *               &lt;enumeration value="2823"/>
 *               &lt;enumeration value="2824"/>
 *               &lt;enumeration value="2829"/>
 *               &lt;enumeration value="2831"/>
 *               &lt;enumeration value="2832"/>
 *               &lt;enumeration value="2839"/>
 *               &lt;enumeration value="2841"/>
 *               &lt;enumeration value="2842"/>
 *               &lt;enumeration value="2849"/>
 *               &lt;enumeration value="2851"/>
 *               &lt;enumeration value="2852"/>
 *               &lt;enumeration value="2853"/>
 *               &lt;enumeration value="2854"/>
 *               &lt;enumeration value="2859"/>
 *               &lt;enumeration value="2861"/>
 *               &lt;enumeration value="2862"/>
 *               &lt;enumeration value="2863"/>
 *               &lt;enumeration value="2864"/>
 *               &lt;enumeration value="2865"/>
 *               &lt;enumeration value="2866"/>
 *               &lt;enumeration value="2867"/>
 *               &lt;enumeration value="2869"/>
 *               &lt;enumeration value="2911"/>
 *               &lt;enumeration value="2919"/>
 *               &lt;enumeration value="2921"/>
 *               &lt;enumeration value="2922"/>
 *               &lt;enumeration value="2923"/>
 *               &lt;enumeration value="2929"/>
 *               &lt;enumeration value="2941"/>
 *               &lt;enumeration value="2942"/>
 *               &lt;enumeration value="2949"/>
 *               &lt;enumeration value="3610"/>
 *               &lt;enumeration value="3620"/>
 *               &lt;enumeration value="3701"/>
 *               &lt;enumeration value="3702"/>
 *               &lt;enumeration value="4111"/>
 *               &lt;enumeration value="4112"/>
 *               &lt;enumeration value="4113"/>
 *               &lt;enumeration value="4121"/>
 *               &lt;enumeration value="4122"/>
 *               &lt;enumeration value="4210"/>
 *               &lt;enumeration value="4221"/>
 *               &lt;enumeration value="4222"/>
 *               &lt;enumeration value="4223"/>
 *               &lt;enumeration value="4224"/>
 *               &lt;enumeration value="4231"/>
 *               &lt;enumeration value="4232"/>
 *               &lt;enumeration value="4233"/>
 *               &lt;enumeration value="4234"/>
 *               &lt;enumeration value="4241"/>
 *               &lt;enumeration value="4242"/>
 *               &lt;enumeration value="4243"/>
 *               &lt;enumeration value="4244"/>
 *               &lt;enumeration value="4245"/>
 *               &lt;enumeration value="4251"/>
 *               &lt;enumeration value="4259"/>
 *               &lt;enumeration value="4511"/>
 *               &lt;enumeration value="4512"/>
 *               &lt;enumeration value="4519"/>
 *               &lt;enumeration value="4521"/>
 *               &lt;enumeration value="4522"/>
 *               &lt;enumeration value="4523"/>
 *               &lt;enumeration value="4531"/>
 *               &lt;enumeration value="4539"/>
 *               &lt;enumeration value="4611"/>
 *               &lt;enumeration value="4612"/>
 *               &lt;enumeration value="4613"/>
 *               &lt;enumeration value="4614"/>
 *               &lt;enumeration value="4615"/>
 *               &lt;enumeration value="4619"/>
 *               &lt;enumeration value="4621"/>
 *               &lt;enumeration value="4622"/>
 *               &lt;enumeration value="4623"/>
 *               &lt;enumeration value="4624"/>
 *               &lt;enumeration value="4711"/>
 *               &lt;enumeration value="4712"/>
 *               &lt;enumeration value="4713"/>
 *               &lt;enumeration value="4714"/>
 *               &lt;enumeration value="4715"/>
 *               &lt;enumeration value="4716"/>
 *               &lt;enumeration value="4717"/>
 *               &lt;enumeration value="4718"/>
 *               &lt;enumeration value="4719"/>
 *               &lt;enumeration value="4721"/>
 *               &lt;enumeration value="4722"/>
 *               &lt;enumeration value="4723"/>
 *               &lt;enumeration value="4731"/>
 *               &lt;enumeration value="4732"/>
 *               &lt;enumeration value="4733"/>
 *               &lt;enumeration value="4739"/>
 *               &lt;enumeration value="4791"/>
 *               &lt;enumeration value="4792"/>
 *               &lt;enumeration value="4793"/>
 *               &lt;enumeration value="4794"/>
 *               &lt;enumeration value="4795"/>
 *               &lt;enumeration value="4796"/>
 *               &lt;enumeration value="4799"/>
 *               &lt;enumeration value="5110"/>
 *               &lt;enumeration value="5121"/>
 *               &lt;enumeration value="5122"/>
 *               &lt;enumeration value="5123"/>
 *               &lt;enumeration value="5124"/>
 *               &lt;enumeration value="5125"/>
 *               &lt;enumeration value="5126"/>
 *               &lt;enumeration value="5129"/>
 *               &lt;enumeration value="5210"/>
 *               &lt;enumeration value="5221"/>
 *               &lt;enumeration value="5222"/>
 *               &lt;enumeration value="5223"/>
 *               &lt;enumeration value="5231"/>
 *               &lt;enumeration value="5232"/>
 *               &lt;enumeration value="5233"/>
 *               &lt;enumeration value="5234"/>
 *               &lt;enumeration value="5235"/>
 *               &lt;enumeration value="5241"/>
 *               &lt;enumeration value="5242"/>
 *               &lt;enumeration value="5243"/>
 *               &lt;enumeration value="5244"/>
 *               &lt;enumeration value="5245"/>
 *               &lt;enumeration value="5251"/>
 *               &lt;enumeration value="5252"/>
 *               &lt;enumeration value="5253"/>
 *               &lt;enumeration value="5254"/>
 *               &lt;enumeration value="5255"/>
 *               &lt;enumeration value="5259"/>
 *               &lt;enumeration value="5261"/>
 *               &lt;enumeration value="5269"/>
 *               &lt;enumeration value="5311"/>
 *               &lt;enumeration value="5312"/>
 *               &lt;enumeration value="5313"/>
 *               &lt;enumeration value="5321"/>
 *               &lt;enumeration value="5322"/>
 *               &lt;enumeration value="5323"/>
 *               &lt;enumeration value="5324"/>
 *               &lt;enumeration value="5329"/>
 *               &lt;enumeration value="5710"/>
 *               &lt;enumeration value="5720"/>
 *               &lt;enumeration value="5730"/>
 *               &lt;enumeration value="5740"/>
 *               &lt;enumeration value="6110"/>
 *               &lt;enumeration value="6121"/>
 *               &lt;enumeration value="6122"/>
 *               &lt;enumeration value="6123"/>
 *               &lt;enumeration value="6200"/>
 *               &lt;enumeration value="6301"/>
 *               &lt;enumeration value="6302"/>
 *               &lt;enumeration value="6303"/>
 *               &lt;enumeration value="6401"/>
 *               &lt;enumeration value="6402"/>
 *               &lt;enumeration value="6403"/>
 *               &lt;enumeration value="6501"/>
 *               &lt;enumeration value="6509"/>
 *               &lt;enumeration value="6611"/>
 *               &lt;enumeration value="6619"/>
 *               &lt;enumeration value="6621"/>
 *               &lt;enumeration value="6622"/>
 *               &lt;enumeration value="6623"/>
 *               &lt;enumeration value="6629"/>
 *               &lt;enumeration value="6630"/>
 *               &lt;enumeration value="6641"/>
 *               &lt;enumeration value="6642"/>
 *               &lt;enumeration value="6643"/>
 *               &lt;enumeration value="6644"/>
 *               &lt;enumeration value="6649"/>
 *               &lt;enumeration value="6701"/>
 *               &lt;enumeration value="6709"/>
 *               &lt;enumeration value="7111"/>
 *               &lt;enumeration value="7112"/>
 *               &lt;enumeration value="7120"/>
 *               &lt;enumeration value="7310"/>
 *               &lt;enumeration value="7314"/>
 *               &lt;enumeration value="7315"/>
 *               &lt;enumeration value="7318"/>
 *               &lt;enumeration value="7319"/>
 *               &lt;enumeration value="7321"/>
 *               &lt;enumeration value="7322"/>
 *               &lt;enumeration value="7323"/>
 *               &lt;enumeration value="7324"/>
 *               &lt;enumeration value="7325"/>
 *               &lt;enumeration value="7326"/>
 *               &lt;enumeration value="7327"/>
 *               &lt;enumeration value="7328"/>
 *               &lt;enumeration value="7329"/>
 *               &lt;enumeration value="7330"/>
 *               &lt;enumeration value="7338"/>
 *               &lt;enumeration value="7340"/>
 *               &lt;enumeration value="7346"/>
 *               &lt;enumeration value="7411"/>
 *               &lt;enumeration value="7412"/>
 *               &lt;enumeration value="7421"/>
 *               &lt;enumeration value="7422"/>
 *               &lt;enumeration value="7511"/>
 *               &lt;enumeration value="7518"/>
 *               &lt;enumeration value="7519"/>
 *               &lt;enumeration value="7520"/>
 *               &lt;enumeration value="7640"/>
 *               &lt;enumeration value="7641"/>
 *               &lt;enumeration value="7650"/>
 *               &lt;enumeration value="7651"/>
 *               &lt;enumeration value="7652"/>
 *               &lt;enumeration value="7653"/>
 *               &lt;enumeration value="7654"/>
 *               &lt;enumeration value="7655"/>
 *               &lt;enumeration value="7656"/>
 *               &lt;enumeration value="7657"/>
 *               &lt;enumeration value="7658"/>
 *               &lt;enumeration value="7659"/>
 *               &lt;enumeration value="7660"/>
 *               &lt;enumeration value="7661"/>
 *               &lt;enumeration value="7662"/>
 *               &lt;enumeration value="7663"/>
 *               &lt;enumeration value="7664"/>
 *               &lt;enumeration value="7665"/>
 *               &lt;enumeration value="7666"/>
 *               &lt;enumeration value="7667"/>
 *               &lt;enumeration value="7668"/>
 *               &lt;enumeration value="7669"/>
 *               &lt;enumeration value="7670"/>
 *               &lt;enumeration value="7671"/>
 *               &lt;enumeration value="7672"/>
 *               &lt;enumeration value="7673"/>
 *               &lt;enumeration value="7674"/>
 *               &lt;enumeration value="7711"/>
 *               &lt;enumeration value="7720"/>
 *               &lt;enumeration value="7730"/>
 *               &lt;enumeration value="7741"/>
 *               &lt;enumeration value="7742"/>
 *               &lt;enumeration value="7743"/>
 *               &lt;enumeration value="7810"/>
 *               &lt;enumeration value="7821"/>
 *               &lt;enumeration value="7822"/>
 *               &lt;enumeration value="7823"/>
 *               &lt;enumeration value="7829"/>
 *               &lt;enumeration value="7831"/>
 *               &lt;enumeration value="7832"/>
 *               &lt;enumeration value="7833"/>
 *               &lt;enumeration value="7834"/>
 *               &lt;enumeration value="7841"/>
 *               &lt;enumeration value="7842"/>
 *               &lt;enumeration value="7851"/>
 *               &lt;enumeration value="7852"/>
 *               &lt;enumeration value="7853"/>
 *               &lt;enumeration value="7854"/>
 *               &lt;enumeration value="7855"/>
 *               &lt;enumeration value="7861"/>
 *               &lt;enumeration value="7862"/>
 *               &lt;enumeration value="7863"/>
 *               &lt;enumeration value="7864"/>
 *               &lt;enumeration value="7865"/>
 *               &lt;enumeration value="7866"/>
 *               &lt;enumeration value="7867"/>
 *               &lt;enumeration value="7869"/>
 *               &lt;enumeration value="8111"/>
 *               &lt;enumeration value="8112"/>
 *               &lt;enumeration value="8113"/>
 *               &lt;enumeration value="8117"/>
 *               &lt;enumeration value="8118"/>
 *               &lt;enumeration value="8120"/>
 *               &lt;enumeration value="8130"/>
 *               &lt;enumeration value="8200"/>
 *               &lt;enumeration value="8410"/>
 *               &lt;enumeration value="8421"/>
 *               &lt;enumeration value="8422"/>
 *               &lt;enumeration value="8423"/>
 *               &lt;enumeration value="8424"/>
 *               &lt;enumeration value="8431"/>
 *               &lt;enumeration value="8432"/>
 *               &lt;enumeration value="8440"/>
 *               &lt;enumeration value="8611"/>
 *               &lt;enumeration value="8612"/>
 *               &lt;enumeration value="8613"/>
 *               &lt;enumeration value="8621"/>
 *               &lt;enumeration value="8622"/>
 *               &lt;enumeration value="8623"/>
 *               &lt;enumeration value="8631"/>
 *               &lt;enumeration value="8632"/>
 *               &lt;enumeration value="8633"/>
 *               &lt;enumeration value="8634"/>
 *               &lt;enumeration value="8635"/>
 *               &lt;enumeration value="8636"/>
 *               &lt;enumeration value="8639"/>
 *               &lt;enumeration value="8640"/>
 *               &lt;enumeration value="8710"/>
 *               &lt;enumeration value="8721"/>
 *               &lt;enumeration value="8722"/>
 *               &lt;enumeration value="8729"/>
 *               &lt;enumeration value="9111"/>
 *               &lt;enumeration value="9112"/>
 *               &lt;enumeration value="9113"/>
 *               &lt;enumeration value="9121"/>
 *               &lt;enumeration value="9122"/>
 *               &lt;enumeration value="9210"/>
 *               &lt;enumeration value="9220"/>
 *               &lt;enumeration value="9231"/>
 *               &lt;enumeration value="9239"/>
 *               &lt;enumeration value="9241"/>
 *               &lt;enumeration value="9242"/>
 *               &lt;enumeration value="9251"/>
 *               &lt;enumeration value="9252"/>
 *               &lt;enumeration value="9259"/>
 *               &lt;enumeration value="9311"/>
 *               &lt;enumeration value="9312"/>
 *               &lt;enumeration value="9319"/>
 *               &lt;enumeration value="9321"/>
 *               &lt;enumeration value="9322"/>
 *               &lt;enumeration value="9329"/>
 *               &lt;enumeration value="9330"/>
 *               &lt;enumeration value="9511"/>
 *               &lt;enumeration value="9519"/>
 *               &lt;enumeration value="9521"/>
 *               &lt;enumeration value="9522"/>
 *               &lt;enumeration value="9523"/>
 *               &lt;enumeration value="9524"/>
 *               &lt;enumeration value="9525"/>
 *               &lt;enumeration value="9526"/>
 *               &lt;enumeration value="9529"/>
 *               &lt;enumeration value="9610"/>
 *               &lt;enumeration value="9621"/>
 *               &lt;enumeration value="9622"/>
 *               &lt;enumeration value="9628"/>
 *               &lt;enumeration value="9629"/>
 *               &lt;enumeration value="9631"/>
 *               &lt;enumeration value="9632"/>
 *               &lt;enumeration value="9633"/>
 *               &lt;enumeration value="9634"/>
 *               &lt;enumeration value="9700"/>
 *               &lt;enumeration value="9900"/>
 *               &lt;enumeration value="9999"/>
 *               &lt;enumeration value="UNKN"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Industry", propOrder = {
    "primaryIndustry",
    "subIndustry"
})
public class Industry {

    @XmlElement(name = "PrimaryIndustry", required = true)
    protected String primaryIndustry;
    @XmlElement(name = "SubIndustry", required = true)
    protected String subIndustry;

    /**
     * Gets the value of the primaryIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryIndustry() {
        return primaryIndustry;
    }

    /**
     * Sets the value of the primaryIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryIndustry(String value) {
        this.primaryIndustry = value;
    }

    /**
     * Gets the value of the subIndustry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubIndustry() {
        return subIndustry;
    }

    /**
     * Sets the value of the subIndustry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubIndustry(String value) {
        this.subIndustry = value;
    }

}
