//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * IncomeProtection
 * 
 * <p>Java class for InsuranceCoverIncomeProtection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsuranceCoverIncomeProtection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Benefit" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *         &lt;element name="Definition">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Agreed"/>
 *               &lt;enumeration value="Indemnity"/>
 *               &lt;enumeration value="Super-Linked"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CoverDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BenefitFrequency" type="{http://www.epistandards.com/4.3}PaymentFrequency" minOccurs="0"/>
 *         &lt;element name="BenefitPeriod" type="{http://www.epistandards.com/4.3}InsuranceIncomeProtectionBenefitPeriod" minOccurs="0"/>
 *         &lt;element name="WaitingPeriod" type="{http://www.epistandards.com/4.3}InsuranceIncomeProtectionWaitingPeriod" minOccurs="0"/>
 *         &lt;element name="CommencementDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="RenewalDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ExpiryDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="PremiumDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PremiumAmount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                   &lt;element name="Indexation" type="{http://www.epistandards.com/4.3}Indexation" minOccurs="0"/>
 *                   &lt;element name="PremiumStructure" type="{http://www.epistandards.com/4.3}InsurancePremiumStructure" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BenefitStatus" type="{http://www.epistandards.com/4.3}InsuranceBenefitStatus" minOccurs="0"/>
 *         &lt;element name="IssueStatus" type="{http://www.epistandards.com/4.3}InsuranceIssueStatus" minOccurs="0"/>
 *         &lt;element name="Loading" type="{http://www.epistandards.com/4.3}InsuranceLoading" minOccurs="0"/>
 *         &lt;element name="Exclusions" type="{http://www.epistandards.com/4.3}InsuranceExclusions" minOccurs="0"/>
 *         &lt;element name="Options" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="9">
 *                   &lt;element name="IncreasingClaim">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="2">
 *                             &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                             &lt;element name="ExpiryAge">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;maxInclusive value="115"/>
 *                                   &lt;minInclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AccidentOption">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="5">
 *                             &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                             &lt;element name="ExpiryAge">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;maxInclusive value="115"/>
 *                                   &lt;minInclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DayX">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="0"/>
 *                                   &lt;maxInclusive value="31"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="QualifyingPeriod">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="1"/>
 *                                   &lt;maxInclusive value="365"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="BenefitPeriod">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;minInclusive value="1"/>
 *                                   &lt;maxInclusive value="365"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="LumpSumOption">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="2">
 *                             &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                             &lt;element name="ExpiryAge">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;maxInclusive value="115"/>
 *                                   &lt;minInclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="TraumaOption">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="2">
 *                             &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                             &lt;element name="ExpiryAge">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;maxInclusive value="115"/>
 *                                   &lt;minInclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AIDSExclusion" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="FutureInsurability" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                   &lt;element name="RetrospectiveBenefit">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="2">
 *                             &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                             &lt;element name="ExpiryAge">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                                   &lt;maxInclusive value="115"/>
 *                                   &lt;minInclusive value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="IsSuper" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                   &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Notes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Note" type="{http://www.epistandards.com/4.3}Note" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Delete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsuranceCoverIncomeProtection", propOrder = {
    "benefit",
    "definition",
    "coverDescription",
    "benefitFrequency",
    "benefitPeriod",
    "waitingPeriod",
    "commencementDate",
    "renewalDate",
    "expiryDate",
    "premiumDetails",
    "benefitStatus",
    "issueStatus",
    "loading",
    "exclusions",
    "options",
    "notes",
    "delete",
    "epiExtension"
})
public class InsuranceCoverIncomeProtection {

    @XmlElement(name = "Benefit", required = true)
    protected MonetaryAmount benefit;
    @XmlElement(name = "Definition", required = true)
    protected String definition;
    @XmlElement(name = "CoverDescription")
    protected String coverDescription;
    @XmlElement(name = "BenefitFrequency")
    protected PaymentFrequency benefitFrequency;
    @XmlElement(name = "BenefitPeriod")
    protected InsuranceIncomeProtectionBenefitPeriod benefitPeriod;
    @XmlElement(name = "WaitingPeriod")
    protected String waitingPeriod;
    @XmlElement(name = "CommencementDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar commencementDate;
    @XmlElement(name = "RenewalDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar renewalDate;
    @XmlElement(name = "ExpiryDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "PremiumDetails")
    protected InsuranceCoverIncomeProtection.PremiumDetails premiumDetails;
    @XmlElement(name = "BenefitStatus")
    protected InsuranceBenefitStatus benefitStatus;
    @XmlElement(name = "IssueStatus")
    protected InsuranceIssueStatus issueStatus;
    @XmlElement(name = "Loading")
    protected InsuranceLoading loading;
    @XmlElement(name = "Exclusions")
    protected InsuranceExclusions exclusions;
    @XmlElement(name = "Options")
    protected InsuranceCoverIncomeProtection.Options options;
    @XmlElement(name = "Notes")
    protected InsuranceCoverIncomeProtection.Notes notes;
    @XmlElement(name = "Delete")
    protected boolean delete;
    @XmlElement(name = "EPIExtension")
    protected EPIExtension epiExtension;

    /**
     * Gets the value of the benefit property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryAmount }
     *     
     */
    public MonetaryAmount getBenefit() {
        return benefit;
    }

    /**
     * Sets the value of the benefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryAmount }
     *     
     */
    public void setBenefit(MonetaryAmount value) {
        this.benefit = value;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

    /**
     * Gets the value of the coverDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverDescription() {
        return coverDescription;
    }

    /**
     * Sets the value of the coverDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverDescription(String value) {
        this.coverDescription = value;
    }

    /**
     * Gets the value of the benefitFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentFrequency }
     *     
     */
    public PaymentFrequency getBenefitFrequency() {
        return benefitFrequency;
    }

    /**
     * Sets the value of the benefitFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentFrequency }
     *     
     */
    public void setBenefitFrequency(PaymentFrequency value) {
        this.benefitFrequency = value;
    }

    /**
     * Gets the value of the benefitPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceIncomeProtectionBenefitPeriod }
     *     
     */
    public InsuranceIncomeProtectionBenefitPeriod getBenefitPeriod() {
        return benefitPeriod;
    }

    /**
     * Sets the value of the benefitPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceIncomeProtectionBenefitPeriod }
     *     
     */
    public void setBenefitPeriod(InsuranceIncomeProtectionBenefitPeriod value) {
        this.benefitPeriod = value;
    }

    /**
     * Gets the value of the waitingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaitingPeriod() {
        return waitingPeriod;
    }

    /**
     * Sets the value of the waitingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaitingPeriod(String value) {
        this.waitingPeriod = value;
    }

    /**
     * Gets the value of the commencementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCommencementDate() {
        return commencementDate;
    }

    /**
     * Sets the value of the commencementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCommencementDate(XMLGregorianCalendar value) {
        this.commencementDate = value;
    }

    /**
     * Gets the value of the renewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRenewalDate() {
        return renewalDate;
    }

    /**
     * Sets the value of the renewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRenewalDate(XMLGregorianCalendar value) {
        this.renewalDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the premiumDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceCoverIncomeProtection.PremiumDetails }
     *     
     */
    public InsuranceCoverIncomeProtection.PremiumDetails getPremiumDetails() {
        return premiumDetails;
    }

    /**
     * Sets the value of the premiumDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceCoverIncomeProtection.PremiumDetails }
     *     
     */
    public void setPremiumDetails(InsuranceCoverIncomeProtection.PremiumDetails value) {
        this.premiumDetails = value;
    }

    /**
     * Gets the value of the benefitStatus property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceBenefitStatus }
     *     
     */
    public InsuranceBenefitStatus getBenefitStatus() {
        return benefitStatus;
    }

    /**
     * Sets the value of the benefitStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceBenefitStatus }
     *     
     */
    public void setBenefitStatus(InsuranceBenefitStatus value) {
        this.benefitStatus = value;
    }

    /**
     * Gets the value of the issueStatus property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceIssueStatus }
     *     
     */
    public InsuranceIssueStatus getIssueStatus() {
        return issueStatus;
    }

    /**
     * Sets the value of the issueStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceIssueStatus }
     *     
     */
    public void setIssueStatus(InsuranceIssueStatus value) {
        this.issueStatus = value;
    }

    /**
     * Gets the value of the loading property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceLoading }
     *     
     */
    public InsuranceLoading getLoading() {
        return loading;
    }

    /**
     * Sets the value of the loading property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceLoading }
     *     
     */
    public void setLoading(InsuranceLoading value) {
        this.loading = value;
    }

    /**
     * Gets the value of the exclusions property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceExclusions }
     *     
     */
    public InsuranceExclusions getExclusions() {
        return exclusions;
    }

    /**
     * Sets the value of the exclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceExclusions }
     *     
     */
    public void setExclusions(InsuranceExclusions value) {
        this.exclusions = value;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceCoverIncomeProtection.Options }
     *     
     */
    public InsuranceCoverIncomeProtection.Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceCoverIncomeProtection.Options }
     *     
     */
    public void setOptions(InsuranceCoverIncomeProtection.Options value) {
        this.options = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceCoverIncomeProtection.Notes }
     *     
     */
    public InsuranceCoverIncomeProtection.Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceCoverIncomeProtection.Notes }
     *     
     */
    public void setNotes(InsuranceCoverIncomeProtection.Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the delete property.
     * 
     */
    public boolean isDelete() {
        return delete;
    }

    /**
     * Sets the value of the delete property.
     * 
     */
    public void setDelete(boolean value) {
        this.delete = value;
    }

    /**
     * Gets the value of the epiExtension property.
     * 
     * @return
     *     possible object is
     *     {@link EPIExtension }
     *     
     */
    public EPIExtension getEPIExtension() {
        return epiExtension;
    }

    /**
     * Sets the value of the epiExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPIExtension }
     *     
     */
    public void setEPIExtension(EPIExtension value) {
        this.epiExtension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Note" type="{http://www.epistandards.com/4.3}Note" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "note"
    })
    public static class Notes {

        @XmlElement(name = "Note", required = true)
        protected List<Note> note;

        /**
         * Gets the value of the note property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the note property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Note }
         * 
         * 
         */
        public List<Note> getNote() {
            if (note == null) {
                note = new ArrayList<Note>();
            }
            return this.note;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="9">
     *         &lt;element name="IncreasingClaim">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="2">
     *                   &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                   &lt;element name="ExpiryAge">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;maxInclusive value="115"/>
     *                         &lt;minInclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AccidentOption">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="5">
     *                   &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                   &lt;element name="ExpiryAge">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;maxInclusive value="115"/>
     *                         &lt;minInclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DayX">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;minInclusive value="0"/>
     *                         &lt;maxInclusive value="31"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="QualifyingPeriod">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;minInclusive value="1"/>
     *                         &lt;maxInclusive value="365"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="BenefitPeriod">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;minInclusive value="1"/>
     *                         &lt;maxInclusive value="365"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="LumpSumOption">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="2">
     *                   &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                   &lt;element name="ExpiryAge">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;maxInclusive value="115"/>
     *                         &lt;minInclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="TraumaOption">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="2">
     *                   &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                   &lt;element name="ExpiryAge">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;maxInclusive value="115"/>
     *                         &lt;minInclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AIDSExclusion" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="FutureInsurability" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *         &lt;element name="RetrospectiveBenefit">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="2">
     *                   &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                   &lt;element name="ExpiryAge">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *                         &lt;maxInclusive value="115"/>
     *                         &lt;minInclusive value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="IsSuper" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "increasingClaimOrAccidentOptionOrLumpSumOption"
    })
    public static class Options {

        @XmlElementRefs({
            @XmlElementRef(name = "IsSuper", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "FutureInsurability", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "TraumaOption", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "LumpSumOption", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "RetrospectiveBenefit", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "AccidentOption", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "EPIExtension", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "AIDSExclusion", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "IncreasingClaim", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> increasingClaimOrAccidentOptionOrLumpSumOption;

        /**
         * Gets the value of the increasingClaimOrAccidentOptionOrLumpSumOption property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the increasingClaimOrAccidentOptionOrLumpSumOption property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIncreasingClaimOrAccidentOptionOrLumpSumOption().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         * {@link JAXBElement }{@code <}{@link MonetaryAmount }{@code >}
         * {@link JAXBElement }{@code <}{@link InsuranceCoverIncomeProtection.Options.LumpSumOption }{@code >}
         * {@link JAXBElement }{@code <}{@link InsuranceCoverIncomeProtection.Options.TraumaOption }{@code >}
         * {@link JAXBElement }{@code <}{@link InsuranceCoverIncomeProtection.Options.AccidentOption }{@code >}
         * {@link JAXBElement }{@code <}{@link InsuranceCoverIncomeProtection.Options.RetrospectiveBenefit }{@code >}
         * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         * {@link JAXBElement }{@code <}{@link EPIExtension }{@code >}
         * {@link JAXBElement }{@code <}{@link InsuranceCoverIncomeProtection.Options.IncreasingClaim }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getIncreasingClaimOrAccidentOptionOrLumpSumOption() {
            if (increasingClaimOrAccidentOptionOrLumpSumOption == null) {
                increasingClaimOrAccidentOptionOrLumpSumOption = new ArrayList<JAXBElement<?>>();
            }
            return this.increasingClaimOrAccidentOptionOrLumpSumOption;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="5">
         *         &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *         &lt;element name="ExpiryAge">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;maxInclusive value="115"/>
         *               &lt;minInclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DayX">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;minInclusive value="0"/>
         *               &lt;maxInclusive value="31"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="QualifyingPeriod">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;minInclusive value="1"/>
         *               &lt;maxInclusive value="365"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="BenefitPeriod">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;minInclusive value="1"/>
         *               &lt;maxInclusive value="365"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "premiumOrExpiryAgeOrDayX"
        })
        public static class AccidentOption {

            @XmlElementRefs({
                @XmlElementRef(name = "QualifyingPeriod", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BenefitPeriod", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DayX", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "ExpiryAge", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Premium", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> premiumOrExpiryAgeOrDayX;

            /**
             * Gets the value of the premiumOrExpiryAgeOrDayX property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the premiumOrExpiryAgeOrDayX property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPremiumOrExpiryAgeOrDayX().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link Integer }{@code >}
             * {@link JAXBElement }{@code <}{@link Integer }{@code >}
             * {@link JAXBElement }{@code <}{@link Integer }{@code >}
             * {@link JAXBElement }{@code <}{@link Integer }{@code >}
             * {@link JAXBElement }{@code <}{@link MonetaryAmount }{@code >}
             * 
             * 
             */
            public List<JAXBElement<?>> getPremiumOrExpiryAgeOrDayX() {
                if (premiumOrExpiryAgeOrDayX == null) {
                    premiumOrExpiryAgeOrDayX = new ArrayList<JAXBElement<?>>();
                }
                return this.premiumOrExpiryAgeOrDayX;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="2">
         *         &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *         &lt;element name="ExpiryAge">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;maxInclusive value="115"/>
         *               &lt;minInclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "premiumOrExpiryAge"
        })
        public static class IncreasingClaim {

            @XmlElements({
                @XmlElement(name = "Premium", type = MonetaryAmount.class),
                @XmlElement(name = "ExpiryAge", type = Integer.class)
            })
            protected List<Object> premiumOrExpiryAge;

            /**
             * Gets the value of the premiumOrExpiryAge property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the premiumOrExpiryAge property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPremiumOrExpiryAge().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MonetaryAmount }
             * {@link Integer }
             * 
             * 
             */
            public List<Object> getPremiumOrExpiryAge() {
                if (premiumOrExpiryAge == null) {
                    premiumOrExpiryAge = new ArrayList<Object>();
                }
                return this.premiumOrExpiryAge;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="2">
         *         &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *         &lt;element name="ExpiryAge">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;maxInclusive value="115"/>
         *               &lt;minInclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "premiumOrExpiryAge"
        })
        public static class LumpSumOption {

            @XmlElements({
                @XmlElement(name = "Premium", type = MonetaryAmount.class),
                @XmlElement(name = "ExpiryAge", type = Integer.class)
            })
            protected List<Object> premiumOrExpiryAge;

            /**
             * Gets the value of the premiumOrExpiryAge property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the premiumOrExpiryAge property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPremiumOrExpiryAge().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MonetaryAmount }
             * {@link Integer }
             * 
             * 
             */
            public List<Object> getPremiumOrExpiryAge() {
                if (premiumOrExpiryAge == null) {
                    premiumOrExpiryAge = new ArrayList<Object>();
                }
                return this.premiumOrExpiryAge;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="2">
         *         &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *         &lt;element name="ExpiryAge">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;maxInclusive value="115"/>
         *               &lt;minInclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "premiumOrExpiryAge"
        })
        public static class RetrospectiveBenefit {

            @XmlElements({
                @XmlElement(name = "Premium", type = MonetaryAmount.class),
                @XmlElement(name = "ExpiryAge", type = Integer.class)
            })
            protected List<Object> premiumOrExpiryAge;

            /**
             * Gets the value of the premiumOrExpiryAge property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the premiumOrExpiryAge property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPremiumOrExpiryAge().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MonetaryAmount }
             * {@link Integer }
             * 
             * 
             */
            public List<Object> getPremiumOrExpiryAge() {
                if (premiumOrExpiryAge == null) {
                    premiumOrExpiryAge = new ArrayList<Object>();
                }
                return this.premiumOrExpiryAge;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="2">
         *         &lt;element name="Premium" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *         &lt;element name="ExpiryAge">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
         *               &lt;maxInclusive value="115"/>
         *               &lt;minInclusive value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "premiumOrExpiryAge"
        })
        public static class TraumaOption {

            @XmlElements({
                @XmlElement(name = "Premium", type = MonetaryAmount.class),
                @XmlElement(name = "ExpiryAge", type = Integer.class)
            })
            protected List<Object> premiumOrExpiryAge;

            /**
             * Gets the value of the premiumOrExpiryAge property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the premiumOrExpiryAge property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPremiumOrExpiryAge().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link MonetaryAmount }
             * {@link Integer }
             * 
             * 
             */
            public List<Object> getPremiumOrExpiryAge() {
                if (premiumOrExpiryAge == null) {
                    premiumOrExpiryAge = new ArrayList<Object>();
                }
                return this.premiumOrExpiryAge;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PremiumAmount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *         &lt;element name="Indexation" type="{http://www.epistandards.com/4.3}Indexation" minOccurs="0"/>
     *         &lt;element name="PremiumStructure" type="{http://www.epistandards.com/4.3}InsurancePremiumStructure" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "premiumAmount",
        "indexation",
        "premiumStructure"
    })
    public static class PremiumDetails {

        @XmlElement(name = "PremiumAmount", required = true)
        protected MonetaryAmount premiumAmount;
        @XmlElement(name = "Indexation")
        protected Indexation indexation;
        @XmlElement(name = "PremiumStructure")
        protected InsurancePremiumStructure premiumStructure;

        /**
         * Gets the value of the premiumAmount property.
         * 
         * @return
         *     possible object is
         *     {@link MonetaryAmount }
         *     
         */
        public MonetaryAmount getPremiumAmount() {
            return premiumAmount;
        }

        /**
         * Sets the value of the premiumAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link MonetaryAmount }
         *     
         */
        public void setPremiumAmount(MonetaryAmount value) {
            this.premiumAmount = value;
        }

        /**
         * Gets the value of the indexation property.
         * 
         * @return
         *     possible object is
         *     {@link Indexation }
         *     
         */
        public Indexation getIndexation() {
            return indexation;
        }

        /**
         * Sets the value of the indexation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Indexation }
         *     
         */
        public void setIndexation(Indexation value) {
            this.indexation = value;
        }

        /**
         * Gets the value of the premiumStructure property.
         * 
         * @return
         *     possible object is
         *     {@link InsurancePremiumStructure }
         *     
         */
        public InsurancePremiumStructure getPremiumStructure() {
            return premiumStructure;
        }

        /**
         * Sets the value of the premiumStructure property.
         * 
         * @param value
         *     allowed object is
         *     {@link InsurancePremiumStructure }
         *     
         */
        public void setPremiumStructure(InsurancePremiumStructure value) {
            this.premiumStructure = value;
        }

    }

}
