//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Intermediary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Intermediary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Adviser">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://www.epistandards.com/4.3}Adviser">
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="DealerGroup">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://www.epistandards.com/4.3}DealerGroup">
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="PrimaryIntermediary" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="UpdatePlatformDetails" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Remuneration" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="2">
 *                   &lt;element name="Initial">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                             &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Ongoing">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                             &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
 *                             &lt;element name="SlidingScale">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Scale" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="AmountFrom" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                                                 &lt;element name="AmountTo" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
 *                                                 &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EPIExtension" type="{http://www.epistandards.com/4.3}EPIExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Intermediary", propOrder = {
    "adviser",
    "dealerGroup",
    "primaryIntermediary",
    "updatePlatformDetails",
    "remuneration",
    "epiExtension"
})
public class Intermediary {

    @XmlElement(name = "Adviser")
    protected Intermediary.Adviser adviser;
    @XmlElement(name = "DealerGroup")
    protected Intermediary.DealerGroup dealerGroup;
    @XmlElement(name = "PrimaryIntermediary")
    protected boolean primaryIntermediary;
    @XmlElement(name = "UpdatePlatformDetails")
    protected Boolean updatePlatformDetails;
    @XmlElement(name = "Remuneration")
    protected Intermediary.Remuneration remuneration;
    @XmlElement(name = "EPIExtension")
    protected EPIExtension epiExtension;

    /**
     * Gets the value of the adviser property.
     * 
     * @return
     *     possible object is
     *     {@link Intermediary.Adviser }
     *     
     */
    public Intermediary.Adviser getAdviser() {
        return adviser;
    }

    /**
     * Sets the value of the adviser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intermediary.Adviser }
     *     
     */
    public void setAdviser(Intermediary.Adviser value) {
        this.adviser = value;
    }

    /**
     * Gets the value of the dealerGroup property.
     * 
     * @return
     *     possible object is
     *     {@link Intermediary.DealerGroup }
     *     
     */
    public Intermediary.DealerGroup getDealerGroup() {
        return dealerGroup;
    }

    /**
     * Sets the value of the dealerGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intermediary.DealerGroup }
     *     
     */
    public void setDealerGroup(Intermediary.DealerGroup value) {
        this.dealerGroup = value;
    }

    /**
     * Gets the value of the primaryIntermediary property.
     * 
     */
    public boolean isPrimaryIntermediary() {
        return primaryIntermediary;
    }

    /**
     * Sets the value of the primaryIntermediary property.
     * 
     */
    public void setPrimaryIntermediary(boolean value) {
        this.primaryIntermediary = value;
    }

    /**
     * Gets the value of the updatePlatformDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUpdatePlatformDetails() {
        return updatePlatformDetails;
    }

    /**
     * Sets the value of the updatePlatformDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUpdatePlatformDetails(Boolean value) {
        this.updatePlatformDetails = value;
    }

    /**
     * Gets the value of the remuneration property.
     * 
     * @return
     *     possible object is
     *     {@link Intermediary.Remuneration }
     *     
     */
    public Intermediary.Remuneration getRemuneration() {
        return remuneration;
    }

    /**
     * Sets the value of the remuneration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Intermediary.Remuneration }
     *     
     */
    public void setRemuneration(Intermediary.Remuneration value) {
        this.remuneration = value;
    }

    /**
     * Gets the value of the epiExtension property.
     * 
     * @return
     *     possible object is
     *     {@link EPIExtension }
     *     
     */
    public EPIExtension getEPIExtension() {
        return epiExtension;
    }

    /**
     * Sets the value of the epiExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPIExtension }
     *     
     */
    public void setEPIExtension(EPIExtension value) {
        this.epiExtension = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.epistandards.com/4.3}Adviser">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Adviser
        extends com.gbst.customdatasource.xplan.domain.Adviser
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.epistandards.com/4.3}DealerGroup">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DealerGroup
        extends com.gbst.customdatasource.xplan.domain.DealerGroup
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="2">
     *         &lt;element name="Initial">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                   &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Ongoing">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                   &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
     *                   &lt;element name="SlidingScale">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Scale" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="AmountFrom" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                                       &lt;element name="AmountTo" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
     *                                       &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "initialOrOngoing"
    })
    public static class Remuneration {

        @XmlElements({
            @XmlElement(name = "Initial", type = Intermediary.Remuneration.Initial.class),
            @XmlElement(name = "Ongoing", type = Intermediary.Remuneration.Ongoing.class)
        })
        protected List<Object> initialOrOngoing;

        /**
         * Gets the value of the initialOrOngoing property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the initialOrOngoing property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInitialOrOngoing().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Intermediary.Remuneration.Initial }
         * {@link Intermediary.Remuneration.Ongoing }
         * 
         * 
         */
        public List<Object> getInitialOrOngoing() {
            if (initialOrOngoing == null) {
                initialOrOngoing = new ArrayList<Object>();
            }
            return this.initialOrOngoing;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *         &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "amount",
            "percentage"
        })
        public static class Initial {

            @XmlElement(name = "Amount")
            protected MonetaryAmount amount;
            @XmlElement(name = "Percentage")
            protected BigDecimal percentage;

            /**
             * Gets the value of the amount property.
             * 
             * @return
             *     possible object is
             *     {@link MonetaryAmount }
             *     
             */
            public MonetaryAmount getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             * @param value
             *     allowed object is
             *     {@link MonetaryAmount }
             *     
             */
            public void setAmount(MonetaryAmount value) {
                this.amount = value;
            }

            /**
             * Gets the value of the percentage property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPercentage() {
                return percentage;
            }

            /**
             * Sets the value of the percentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPercentage(BigDecimal value) {
                this.percentage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="Amount" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *         &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
         *         &lt;element name="SlidingScale">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Scale" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="AmountFrom" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *                             &lt;element name="AmountTo" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
         *                             &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "amount",
            "percentage",
            "slidingScale"
        })
        public static class Ongoing {

            @XmlElement(name = "Amount")
            protected MonetaryAmount amount;
            @XmlElement(name = "Percentage")
            protected BigDecimal percentage;
            @XmlElement(name = "SlidingScale")
            protected Intermediary.Remuneration.Ongoing.SlidingScale slidingScale;

            /**
             * Gets the value of the amount property.
             * 
             * @return
             *     possible object is
             *     {@link MonetaryAmount }
             *     
             */
            public MonetaryAmount getAmount() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             * @param value
             *     allowed object is
             *     {@link MonetaryAmount }
             *     
             */
            public void setAmount(MonetaryAmount value) {
                this.amount = value;
            }

            /**
             * Gets the value of the percentage property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getPercentage() {
                return percentage;
            }

            /**
             * Sets the value of the percentage property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setPercentage(BigDecimal value) {
                this.percentage = value;
            }

            /**
             * Gets the value of the slidingScale property.
             * 
             * @return
             *     possible object is
             *     {@link Intermediary.Remuneration.Ongoing.SlidingScale }
             *     
             */
            public Intermediary.Remuneration.Ongoing.SlidingScale getSlidingScale() {
                return slidingScale;
            }

            /**
             * Sets the value of the slidingScale property.
             * 
             * @param value
             *     allowed object is
             *     {@link Intermediary.Remuneration.Ongoing.SlidingScale }
             *     
             */
            public void setSlidingScale(Intermediary.Remuneration.Ongoing.SlidingScale value) {
                this.slidingScale = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Scale" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="AmountFrom" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
             *                   &lt;element name="AmountTo" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
             *                   &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "scale"
            })
            public static class SlidingScale {

                @XmlElement(name = "Scale", required = true)
                protected List<Intermediary.Remuneration.Ongoing.SlidingScale.Scale> scale;

                /**
                 * Gets the value of the scale property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the scale property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getScale().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Intermediary.Remuneration.Ongoing.SlidingScale.Scale }
                 * 
                 * 
                 */
                public List<Intermediary.Remuneration.Ongoing.SlidingScale.Scale> getScale() {
                    if (scale == null) {
                        scale = new ArrayList<Intermediary.Remuneration.Ongoing.SlidingScale.Scale>();
                    }
                    return this.scale;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="AmountFrom" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
                 *         &lt;element name="AmountTo" type="{http://www.epistandards.com/4.3}MonetaryAmount"/>
                 *         &lt;element name="Percentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "amountFrom",
                    "amountTo",
                    "percentage"
                })
                public static class Scale {

                    @XmlElement(name = "AmountFrom", required = true)
                    protected MonetaryAmount amountFrom;
                    @XmlElement(name = "AmountTo", required = true)
                    protected MonetaryAmount amountTo;
                    @XmlElement(name = "Percentage", required = true)
                    protected BigDecimal percentage;

                    /**
                     * Gets the value of the amountFrom property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link MonetaryAmount }
                     *     
                     */
                    public MonetaryAmount getAmountFrom() {
                        return amountFrom;
                    }

                    /**
                     * Sets the value of the amountFrom property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link MonetaryAmount }
                     *     
                     */
                    public void setAmountFrom(MonetaryAmount value) {
                        this.amountFrom = value;
                    }

                    /**
                     * Gets the value of the amountTo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link MonetaryAmount }
                     *     
                     */
                    public MonetaryAmount getAmountTo() {
                        return amountTo;
                    }

                    /**
                     * Sets the value of the amountTo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link MonetaryAmount }
                     *     
                     */
                    public void setAmountTo(MonetaryAmount value) {
                        this.amountTo = value;
                    }

                    /**
                     * Gets the value of the percentage property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getPercentage() {
                        return percentage;
                    }

                    /**
                     * Sets the value of the percentage property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setPercentage(BigDecimal value) {
                        this.percentage = value;
                    }

                }

            }

        }

    }

}
