//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * InvestmentHolding for Account Opening Instruction
 * 
 * <p>Java class for InvestmentHolding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvestmentHolding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InvestmentCode" type="{http://www.epistandards.com/4.3}InvestmentCode"/>
 *         &lt;element name="InvestmentName" type="{http://www.epistandards.com/4.3}InvestmentName" minOccurs="0"/>
 *         &lt;element name="HoldingId" type="{http://www.epistandards.com/4.3}Identifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvestmentHolding", propOrder = {
    "investmentCode",
    "investmentName",
    "holdingId"
})
public class InvestmentHolding {

    @XmlElement(name = "InvestmentCode", required = true)
    protected String investmentCode;
    @XmlElement(name = "InvestmentName")
    protected String investmentName;
    @XmlElement(name = "HoldingId")
    protected String holdingId;

    /**
     * Gets the value of the investmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestmentCode() {
        return investmentCode;
    }

    /**
     * Sets the value of the investmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestmentCode(String value) {
        this.investmentCode = value;
    }

    /**
     * Gets the value of the investmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestmentName() {
        return investmentName;
    }

    /**
     * Sets the value of the investmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestmentName(String value) {
        this.investmentName = value;
    }

    /**
     * Gets the value of the holdingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoldingId() {
        return holdingId;
    }

    /**
     * Sets the value of the holdingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoldingId(String value) {
        this.holdingId = value;
    }

}
