//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LiabilityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LiabilityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="COJS"/>
 *     &lt;enumeration value="COLD"/>
 *     &lt;enumeration value="LTCL"/>
 *     &lt;enumeration value="LTEL"/>
 *     &lt;enumeration value="LTGL"/>
 *     &lt;enumeration value="LTIP"/>
 *     &lt;enumeration value="LTPL"/>
 *     &lt;enumeration value="LTPR"/>
 *     &lt;enumeration value="LTPI"/>
 *     &lt;enumeration value="LTLM"/>
 *     &lt;enumeration value="LTII"/>
 *     &lt;enumeration value="STCC"/>
 *     &lt;enumeration value="STOP"/>
 *     &lt;enumeration value="STOD"/>
 *     &lt;enumeration value="STGL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LiabilityType")
@XmlEnum
public enum LiabilityType {


    /**
     * Contingent - Joint and Several
     * 
     */
    COJS,

    /**
     * Contingent - Limited
     * 
     */
    COLD,

    /**
     * Long term - Car Loan
     * 
     */
    LTCL,

    /**
     * Long term - Education loan
     * 
     */
    LTEL,

    /**
     * Long term - General / Other Loan
     * 
     */
    LTGL,

    /**
     * Long term - Investment Property Mortgage
     * 
     */
    LTIP,

    /**
     * Long Term - Personal Loan
     * 
     */
    LTPL,

    /**
     * Long term - Primary Residance Loan
     * 
     */
    LTPR,

    /**
     * Long term - Primary Residence Islamic Mortgage
     * 
     */
    LTPI,

    /**
     * Long term - Buy to Let Mortgage
     * 
     */
    LTLM,

    /**
     * Long term - Investment Property Islamic Mortgage
     * 
     */
    LTII,

    /**
     * Current / Short term - Credit Card
     * 
     */
    STCC,

    /**
     * Current / Short term - Outstanding Payments
     * 
     */
    STOP,

    /**
     * Current / Short term - Overdraft
     * 
     */
    STOD,

    /**
     * Current / Short term - general/other Loan
     * 
     */
    STGL;

    public String value() {
        return name();
    }

    public static LiabilityType fromValue(String v) {
        return valueOf(v);
    }

}
