//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//


package com.gbst.customdatasource.xplan.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for OccupationDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OccupationDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="Employed">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="EmployerName">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;minLength value="1"/>
 *                           &lt;maxLength value="150"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="ContactName">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;minLength value="1"/>
 *                           &lt;maxLength value="150"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="ContactDetails" type="{http://www.epistandards.com/4.3}ContactDetails"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="SelfEmployed">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="PartnershipPercentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
 *                     &lt;element name="BusinessPartners" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="BusinessPartner" type="{http://www.epistandards.com/4.3}EntityPersonShort" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="Position">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="3">
 *                   &lt;element name="Occupation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Description">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="150"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Industry" type="{http://www.epistandards.com/4.3}Industry" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="IllustrationSoftwareOccupation">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="200"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="UnderwriterOccupation">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="200"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="HoursWorked" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="Duties" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="6">
 *                   &lt;element name="AdministrationSedentary" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
 *                   &lt;element name="SupervisingManualWork" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
 *                   &lt;element name="LightManualWork" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
 *                   &lt;element name="HeavyManualWork" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
 *                   &lt;element name="SiteVisitsInspections" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
 *                   &lt;element name="OtherDuties" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Qualificiations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Qualificiation" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="150"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Period" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CommencementDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="FinishDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PrimaryOccupation" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OccupationDetails", propOrder = {
    "employed",
    "selfEmployed",
    "position",
    "hoursWorked",
    "duties",
    "qualificiations",
    "period",
    "primaryOccupation"
})
public class OccupationDetails {

    @XmlElement(name = "Employed")
    protected OccupationDetails.Employed employed;
    @XmlElement(name = "SelfEmployed")
    protected OccupationDetails.SelfEmployed selfEmployed;
    @XmlElement(name = "Position", required = true)
    protected OccupationDetails.Position position;
    @XmlElement(name = "HoursWorked")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger hoursWorked;
    @XmlElement(name = "Duties")
    protected OccupationDetails.Duties duties;
    @XmlElement(name = "Qualificiations")
    protected OccupationDetails.Qualificiations qualificiations;
    @XmlElement(name = "Period")
    protected OccupationDetails.Period period;
    @XmlElement(name = "PrimaryOccupation")
    protected Boolean primaryOccupation;

    /**
     * Gets the value of the employed property.
     * 
     * @return
     *     possible object is
     *     {@link OccupationDetails.Employed }
     *     
     */
    public OccupationDetails.Employed getEmployed() {
        return employed;
    }

    /**
     * Sets the value of the employed property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupationDetails.Employed }
     *     
     */
    public void setEmployed(OccupationDetails.Employed value) {
        this.employed = value;
    }

    /**
     * Gets the value of the selfEmployed property.
     * 
     * @return
     *     possible object is
     *     {@link OccupationDetails.SelfEmployed }
     *     
     */
    public OccupationDetails.SelfEmployed getSelfEmployed() {
        return selfEmployed;
    }

    /**
     * Sets the value of the selfEmployed property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupationDetails.SelfEmployed }
     *     
     */
    public void setSelfEmployed(OccupationDetails.SelfEmployed value) {
        this.selfEmployed = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link OccupationDetails.Position }
     *     
     */
    public OccupationDetails.Position getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupationDetails.Position }
     *     
     */
    public void setPosition(OccupationDetails.Position value) {
        this.position = value;
    }

    /**
     * Gets the value of the hoursWorked property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHoursWorked() {
        return hoursWorked;
    }

    /**
     * Sets the value of the hoursWorked property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHoursWorked(BigInteger value) {
        this.hoursWorked = value;
    }

    /**
     * Gets the value of the duties property.
     * 
     * @return
     *     possible object is
     *     {@link OccupationDetails.Duties }
     *     
     */
    public OccupationDetails.Duties getDuties() {
        return duties;
    }

    /**
     * Sets the value of the duties property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupationDetails.Duties }
     *     
     */
    public void setDuties(OccupationDetails.Duties value) {
        this.duties = value;
    }

    /**
     * Gets the value of the qualificiations property.
     * 
     * @return
     *     possible object is
     *     {@link OccupationDetails.Qualificiations }
     *     
     */
    public OccupationDetails.Qualificiations getQualificiations() {
        return qualificiations;
    }

    /**
     * Sets the value of the qualificiations property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupationDetails.Qualificiations }
     *     
     */
    public void setQualificiations(OccupationDetails.Qualificiations value) {
        this.qualificiations = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link OccupationDetails.Period }
     *     
     */
    public OccupationDetails.Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccupationDetails.Period }
     *     
     */
    public void setPeriod(OccupationDetails.Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the primaryOccupation property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimaryOccupation() {
        return primaryOccupation;
    }

    /**
     * Sets the value of the primaryOccupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimaryOccupation(Boolean value) {
        this.primaryOccupation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="6">
     *         &lt;element name="AdministrationSedentary" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
     *         &lt;element name="SupervisingManualWork" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
     *         &lt;element name="LightManualWork" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
     *         &lt;element name="HeavyManualWork" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
     *         &lt;element name="SiteVisitsInspections" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
     *         &lt;element name="OtherDuties" type="{http://www.epistandards.com/4.3}OccupationDuties"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "administrationSedentaryOrSupervisingManualWorkOrLightManualWork"
    })
    public static class Duties {

        @XmlElementRefs({
            @XmlElementRef(name = "OtherDuties", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "HeavyManualWork", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "LightManualWork", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "SupervisingManualWork", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "SiteVisitsInspections", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "AdministrationSedentary", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<OccupationDuties>> administrationSedentaryOrSupervisingManualWorkOrLightManualWork;

        /**
         * Gets the value of the administrationSedentaryOrSupervisingManualWorkOrLightManualWork property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the administrationSedentaryOrSupervisingManualWorkOrLightManualWork property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdministrationSedentaryOrSupervisingManualWorkOrLightManualWork().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link OccupationDuties }{@code >}
         * {@link JAXBElement }{@code <}{@link OccupationDuties }{@code >}
         * {@link JAXBElement }{@code <}{@link OccupationDuties }{@code >}
         * {@link JAXBElement }{@code <}{@link OccupationDuties }{@code >}
         * {@link JAXBElement }{@code <}{@link OccupationDuties }{@code >}
         * {@link JAXBElement }{@code <}{@link OccupationDuties }{@code >}
         * 
         * 
         */
        public List<JAXBElement<OccupationDuties>> getAdministrationSedentaryOrSupervisingManualWorkOrLightManualWork() {
            if (administrationSedentaryOrSupervisingManualWorkOrLightManualWork == null) {
                administrationSedentaryOrSupervisingManualWorkOrLightManualWork = new ArrayList<JAXBElement<OccupationDuties>>();
            }
            return this.administrationSedentaryOrSupervisingManualWorkOrLightManualWork;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EmployerName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="150"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ContactName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="150"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ContactDetails" type="{http://www.epistandards.com/4.3}ContactDetails"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employerName",
        "contactName",
        "contactDetails"
    })
    public static class Employed {

        @XmlElement(name = "EmployerName", required = true)
        protected String employerName;
        @XmlElement(name = "ContactName", required = true)
        protected String contactName;
        @XmlElement(name = "ContactDetails", required = true)
        protected ContactDetails contactDetails;

        /**
         * Gets the value of the employerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmployerName() {
            return employerName;
        }

        /**
         * Sets the value of the employerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmployerName(String value) {
            this.employerName = value;
        }

        /**
         * Gets the value of the contactName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactName() {
            return contactName;
        }

        /**
         * Sets the value of the contactName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactName(String value) {
            this.contactName = value;
        }

        /**
         * Gets the value of the contactDetails property.
         * 
         * @return
         *     possible object is
         *     {@link ContactDetails }
         *     
         */
        public ContactDetails getContactDetails() {
            return contactDetails;
        }

        /**
         * Sets the value of the contactDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link ContactDetails }
         *     
         */
        public void setContactDetails(ContactDetails value) {
            this.contactDetails = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CommencementDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="FinishDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "commencementDate",
        "finishDate"
    })
    public static class Period {

        @XmlElement(name = "CommencementDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar commencementDate;
        @XmlElement(name = "FinishDate")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar finishDate;

        /**
         * Gets the value of the commencementDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCommencementDate() {
            return commencementDate;
        }

        /**
         * Sets the value of the commencementDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCommencementDate(XMLGregorianCalendar value) {
            this.commencementDate = value;
        }

        /**
         * Gets the value of the finishDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFinishDate() {
            return finishDate;
        }

        /**
         * Sets the value of the finishDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFinishDate(XMLGregorianCalendar value) {
            this.finishDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="3">
     *         &lt;element name="Occupation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Description">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="150"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Industry" type="{http://www.epistandards.com/4.3}Industry" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="IllustrationSoftwareOccupation">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="200"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="UnderwriterOccupation">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="200"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "occupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation"
    })
    public static class Position {

        @XmlElementRefs({
            @XmlElementRef(name = "IllustrationSoftwareOccupation", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "UnderwriterOccupation", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Occupation", namespace = "http://www.epistandards.com/4.3", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> occupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation;

        /**
         * Gets the value of the occupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the occupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOccupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link OccupationDetails.Position.Occupation }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getOccupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation() {
            if (occupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation == null) {
                occupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation = new ArrayList<JAXBElement<?>>();
            }
            return this.occupationOrIllustrationSoftwareOccupationOrUnderwriterOccupation;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Description">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="150"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Industry" type="{http://www.epistandards.com/4.3}Industry" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description",
            "industry"
        })
        public static class Occupation {

            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlElement(name = "Industry")
            protected Industry industry;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the industry property.
             * 
             * @return
             *     possible object is
             *     {@link Industry }
             *     
             */
            public Industry getIndustry() {
                return industry;
            }

            /**
             * Sets the value of the industry property.
             * 
             * @param value
             *     allowed object is
             *     {@link Industry }
             *     
             */
            public void setIndustry(Industry value) {
                this.industry = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Qualificiation" maxOccurs="unbounded">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="150"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "qualificiation"
    })
    public static class Qualificiations {

        @XmlElement(name = "Qualificiation", required = true)
        protected List<String> qualificiation;

        /**
         * Gets the value of the qualificiation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the qualificiation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQualificiation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getQualificiation() {
            if (qualificiation == null) {
                qualificiation = new ArrayList<String>();
            }
            return this.qualificiation;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PartnershipPercentage" type="{http://www.epistandards.com/4.3}PositivePercentage"/>
     *         &lt;element name="BusinessPartners" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BusinessPartner" type="{http://www.epistandards.com/4.3}EntityPersonShort" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partnershipPercentage",
        "businessPartners"
    })
    public static class SelfEmployed {

        @XmlElement(name = "PartnershipPercentage", required = true)
        protected BigDecimal partnershipPercentage;
        @XmlElement(name = "BusinessPartners")
        protected OccupationDetails.SelfEmployed.BusinessPartners businessPartners;

        /**
         * Gets the value of the partnershipPercentage property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPartnershipPercentage() {
            return partnershipPercentage;
        }

        /**
         * Sets the value of the partnershipPercentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPartnershipPercentage(BigDecimal value) {
            this.partnershipPercentage = value;
        }

        /**
         * Gets the value of the businessPartners property.
         * 
         * @return
         *     possible object is
         *     {@link OccupationDetails.SelfEmployed.BusinessPartners }
         *     
         */
        public OccupationDetails.SelfEmployed.BusinessPartners getBusinessPartners() {
            return businessPartners;
        }

        /**
         * Sets the value of the businessPartners property.
         * 
         * @param value
         *     allowed object is
         *     {@link OccupationDetails.SelfEmployed.BusinessPartners }
         *     
         */
        public void setBusinessPartners(OccupationDetails.SelfEmployed.BusinessPartners value) {
            this.businessPartners = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BusinessPartner" type="{http://www.epistandards.com/4.3}EntityPersonShort" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "businessPartner"
        })
        public static class BusinessPartners {

            @XmlElement(name = "BusinessPartner", required = true)
            protected List<EntityPersonShort> businessPartner;

            /**
             * Gets the value of the businessPartner property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the businessPartner property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBusinessPartner().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link EntityPersonShort }
             * 
             * 
             */
            public List<EntityPersonShort> getBusinessPartner() {
                if (businessPartner == null) {
                    businessPartner = new ArrayList<EntityPersonShort>();
                }
                return this.businessPartner;
            }

        }

    }

}
