//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 02:11:13 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.epistandards.com/4.3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gbst.customdatasource.xplan.domain;
